<?php
require __DIR__.'/app/core.php';
require_once __DIR__.'/app/maintenance.php';
require_once __DIR__.'/app/public_site.php';
if(!installed()){header('Location: install.php');exit;}
ensure_install_lock();
/* v1.7.0: API za nadogradnju koju pokreće firma iz svog ERP-a (bez prijave korisnika, potpisano ključem agenta). */
if(isset($_GET['api'])){require_once __DIR__.'/app/update_api.php';update_api_handle();}
/* v1.9.0: javni cjenik i konfigurator (bez prijave i bez sesije) — erp.mmc.ba/cjenik */
if(($_GET['page']??'')==='cjenik')pub_entry();
start_session();$page=$_GET['page']??(user()?'dashboard':'login');
/* v1.8.0: odjava samo POST-om sa sigurnosnim tokenom (link s druge stranice ne može odjaviti korisnika). */
if($page==='logout'){
 if($_SERVER['REQUEST_METHOD']==='POST'&&hash_equals($_SESSION['csrf']??'',(string)($_POST['csrf']??''))){
  if(user())audit('LOGOUT','user',(int)(user()['id']??0));
  logout_session('logout');header('Location: ./?page=login');exit;
 }
 header('Location: ./?page='.(user()?'dashboard':'login'));exit;
}
if($page==='login'){
 if(user()){header('Location: ?page=dashboard');exit;}
 $err='';$email='';$notice=(string)($_SESSION['auth_notice']??'');unset($_SESSION['auth_notice']);
 if($_SERVER['REQUEST_METHOD']==='POST'){
  $email=trim((string)($_POST['email']??''));
  try{
   if(!hash_equals($_SESSION['csrf']??'',(string)($_POST['csrf']??'')))throw new DomainException('Sigurnosni token je istekao. Osvježi stranicu i pokušaj ponovno.');
   $wait=login_locked_for($email);
   if($wait>0)throw new DomainException('Previše neuspjelih pokušaja. Prijava je privremeno blokirana — pokušaj ponovno za '.max(1,(int)ceil($wait/60)).' min.');
   $u=q('SELECT * FROM users WHERE email=? AND active=1',[$email])->fetch();
   if($u&&password_verify((string)($_POST['password']??''),$u['password_hash'])){
    login_clear_fails($email);login_session($u);
    if(password_needs_rehash($u['password_hash'],PASSWORD_DEFAULT))q('UPDATE users SET password_hash=? WHERE id=?',[password_hash((string)$_POST['password'],PASSWORD_DEFAULT),$u['id']]);
    audit('LOGIN','user',(int)$u['id']);header('Location: ?page=dashboard');exit;
   }
   login_register_fail($email);
   try{q('INSERT INTO audit_log(user_email,action,entity,entity_id,meta_json,created_at) VALUES(?,?,?,?,?,NOW())',[mb_substr($email,0,190),'LOGIN_FAILED','user',null,json_encode(['ip'=>(string)($_SERVER['REMOTE_ADDR']??'')])]);}catch(Throwable $e){}
   $err='Pogrešan email ili lozinka.';
  }catch(DomainException $e){$err=$e->getMessage();}
  catch(Throwable $e){error_log('CC login: '.$e->getMessage());$err='Prijava trenutno nije moguća (greška baze). Pokušaj ponovno ili provjeri server log.';}
 }
 $info=isset($_GET['installed'])?'Platforma je instalirana. Prijavi se administratorskim računom.':($notice==='logout'?'Uspješno ste se odjavili.':($notice==='expired'?'Sesija je istekla zbog neaktivnosti. Prijavite se ponovno.':''));
 header('X-Frame-Options: DENY');header('Referrer-Policy: same-origin');
 ?><!doctype html><html lang="bs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#061a2e"><title>Prijava · MMC ERP Control Center</title><link rel="stylesheet" href="public/style.css?v=<?=e(cc_version())?>"></head>
<body class="auth">
<main class="auth-shell">
 <section class="auth-art" aria-hidden="true"><div class="auth-art-foot"><b>M-M-C d.o.o. Orašje</b><span>Centralno upravljanje firmama, modulima i Core nadogradnjama</span></div></section>
 <section class="auth-side">
  <div class="auth-card">
   <div class="auth-brand"><span class="brand-mark">MMC</span> <b>ERP</b><small>PLATFORM CONTROL CENTER</small></div>
   <h1>Prijava</h1>
   <p class="auth-lead">Prijavite se administratorskim računom za upravljanje ERP instancama.</p>
   <?php if($info):?><div class="alert ok" role="status"><?=e($info)?></div><?php endif;if($err):?><div class="alert err" role="alert"><?=e($err)?></div><?php endif;?>
   <form method="post" class="auth-form" id="authForm" novalidate>
    <input type="hidden" name="csrf" value="<?=e(csrf())?>">
    <div class="auth-field"><label for="authEmail">Email adresa</label><input id="authEmail" type="email" name="email" value="<?=e($email)?>" required <?=$email===''?'autofocus':''?> autocomplete="username" inputmode="email" spellcheck="false" placeholder="ime@firma.ba"></div>
    <div class="auth-field"><label for="authPass">Lozinka</label><div class="auth-pass"><input id="authPass" type="password" name="password" required <?=$email!==''?'autofocus':''?> autocomplete="current-password" placeholder="Unesite lozinku"><button type="button" class="auth-eye" id="authEye" aria-label="Prikaži lozinku" aria-pressed="false">Prikaži</button></div><small class="auth-caps" id="authCaps" hidden>Caps Lock je uključen.</small></div>
    <button class="auth-submit" id="authSubmit" type="submit">Prijava</button>
   </form>
   <div class="auth-foot"><span><i></i> Zaštićena veza · sesija ističe nakon 60 min neaktivnosti</span><span>v<?=e(cc_version())?></span></div>
  </div>
  <p class="auth-copy">© <?=date('Y')?> M-M-C d.o.o. · MMC ERP Platform</p>
 </section>
</main>
<script>(function(){var p=document.getElementById('authPass'),b=document.getElementById('authEye'),c=document.getElementById('authCaps'),f=document.getElementById('authForm'),s=document.getElementById('authSubmit');
b.addEventListener('click',function(){var show=p.type==='password';p.type=show?'text':'password';b.textContent=show?'Sakrij':'Prikaži';b.setAttribute('aria-pressed',show);b.setAttribute('aria-label',show?'Sakrij lozinku':'Prikaži lozinku');p.focus();});
function caps(e){if(e.getModifierState)c.hidden=!e.getModifierState('CapsLock');}p.addEventListener('keyup',caps);p.addEventListener('keydown',caps);
f.addEventListener('submit',function(e){if(!f.checkValidity()){e.preventDefault();f.reportValidity();return;}s.disabled=true;s.textContent='Prijava…';});})();</script>
</body></html><?php exit;
}
require_login();
agent_schema();
commercial_schema();
inquiry_schema();
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{check_csrf();$act=$_POST['action']??'';
  if($act==='save_tenant'){
   $id=(int)($_POST['id']??0);
   $profile=profile_alias((string)($_POST['profile']??''));if(!isset(tenant_profiles()[$profile]))$profile='retail';
   foreach(['base_url'=>'URL instance','agent_url'=>'Update Agent URL'] as $uk=>$ul){$uv=trim((string)($_POST[$uk]??''));if($uv!==''&&!preg_match('~^https?://[^\s"<>]+$~i',$uv))throw new RuntimeException($ul.' mora počinjati s http:// ili https://.');}
   if(!in_array($_POST['status']??'',['ACTIVE','PAUSED','MAINTENANCE'],true))$_POST['status']='ACTIVE';
   /* v1.8.0: slug je ključ firme (paketi s tenant_slugs, API) — samo mala slova, brojke i crtica, jedinstven. */
   $_POST['slug']=strtolower(trim((string)($_POST['slug']??'')));
   if(!preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/',$_POST['slug']))throw new RuntimeException('Slug smije sadržavati samo mala slova, brojke i crticu (npr. optika-isic).');
   if(trim((string)($_POST['name']??''))==='')throw new RuntimeException('Naziv firme je obavezan.');
   if(q('SELECT id FROM tenants WHERE slug=? AND id<>?',[$_POST['slug'],$id])->fetchColumn())throw new RuntimeException('Firma sa slugom "'.$_POST['slug'].'" već postoji.');
   if(!in_array($_POST['fiscal_driver']??'',['NONE','TRING','DATECS'],true))$_POST['fiscal_driver']='NONE';
   $vals=[
     trim($_POST['name']),trim($_POST['slug']),trim($_POST['industry']),rtrim(trim($_POST['base_url']),'/'),
     trim($_POST['db_name']),trim($_POST['installed_version']),trim($_POST['target_version']),$_POST['fiscal_driver'],
     trim($_POST['jib']),trim($_POST['pdv']),$_POST['status'],$profile,trim($_POST['db_user']??''),
     trim($_POST['address']??''),trim($_POST['city']??''),trim($_POST['postal_code']??''),trim($_POST['country']??'Bosna i Hercegovina')
   ];
   if($id){
     q('UPDATE tenants SET name=?,slug=?,industry=?,base_url=?,db_name=?,installed_version=?,target_version=?,fiscal_driver=?,jib=?,pdv=?,status=?,profile=?,db_user=?,address=?,city=?,postal_code=?,country=?,updated_at=NOW() WHERE id=?',array_merge($vals,[$id]));
   }else{
     q('INSERT INTO tenants(name,slug,industry,base_url,db_name,installed_version,target_version,fiscal_driver,jib,pdv,status,profile,db_user,address,city,postal_code,country,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',$vals);
     $id=(int)db()->lastInsertId();
   }
   q('UPDATE tenants SET agent_url=? WHERE id=?',[trim($_POST['agent_url']??''),$id]);
   /* v1.7.1: tajni ključ se ne ispisuje u formi; prazno polje = zadrži postojeći, "-" = obriši. */
   $sec=trim((string)($_POST['agent_secret']??''));if($sec==='-')q('UPDATE tenants SET agent_secret=NULL WHERE id=?',[$id]);elseif($sec!=='')q('UPDATE tenants SET agent_secret=? WHERE id=?',[$sec,$id]);
   q('DELETE FROM tenant_modules WHERE tenant_id=?',[$id]);
   foreach(resolve_module_dependencies((array)($_POST['modules']??[])) as $m)if(isset(modules_catalog()[$m]))q('INSERT INTO tenant_modules(tenant_id,module_key,enabled) VALUES(?,?,1)',[$id,$m]);
   audit('TENANT_SAVE','tenant',$id,['profile'=>$profile]);
   header('Location: ?page=tenant&id='.$id.'&saved=1');exit;
 }
  if($act==='save_module_center'){$tid=(int)($_POST['tenant_id']??0);$t=q('SELECT * FROM tenants WHERE id=?',[$tid])->fetch();if(!$t)throw new RuntimeException('Firma nije pronađena.');$mods=resolve_module_dependencies((array)($_POST['modules']??[]));q('DELETE FROM tenant_modules WHERE tenant_id=?',[$tid]);foreach($mods as $m)if(isset(modules_catalog()[$m]))q('INSERT INTO tenant_modules(tenant_id,module_key,enabled) VALUES(?,?,1)',[$tid,$m]);audit('MODULE_CENTER_SAVE','tenant',$tid,['modules'=>$mods]);header('Location: ?page=modules&tenant='.$tid.'&saved=1');exit;}
  if($act==='inquiry_update'){
   $id=(int)($_POST['id']??0);$iq=q('SELECT id,status FROM inquiries WHERE id=?',[$id])->fetch();if(!$iq)throw new RuntimeException('Upit nije pronađen.');
   $st=(string)($_POST['status']??'');if(!isset(inquiry_statuses()[$st]))$st=$iq['status'];
   q('UPDATE inquiries SET status=?,internal_note=?,updated_at=NOW() WHERE id=?',[$st,trim((string)($_POST['internal_note']??''))?:null,$id]);
   audit('INQUIRY_UPDATE','inquiry',$id,['status'=>$st]);header('Location: ?page=inquiry&id='.$id.'&saved=1');exit;
  }
  if($act==='inquiry_delete'){
   if(!is_admin())throw new RuntimeException('Samo administrator može brisati upite.');
   $id=(int)($_POST['id']??0);q('DELETE FROM inquiries WHERE id=?',[$id]);audit('INQUIRY_DELETE','inquiry',$id);header('Location: ?page=inquiries&deleted=1');exit;
  }
  if($act==='inquiry_to_offer'){
   $id=(int)($_POST['id']??0);$iq=q('SELECT * FROM inquiries WHERE id=?',[$id])->fetch();if(!$iq)throw new RuntimeException('Upit nije pronađen.');
   if(!empty($iq['offer_id'])&&q('SELECT id FROM offers WHERE id=?',[(int)$iq['offer_id']])->fetch()){header('Location: ?page=offer&id='.(int)$iq['offer_id']);exit;}
   $cfg=json_decode((string)$iq['config_json'],true);if(!is_array($cfg)||empty($cfg['lines']))throw new RuntimeException('Ovaj upit nema konfiguraciju za ponudu.');
   $sub=0.0;$items=[];foreach($cfg['lines'] as $ln){$amt=round((float)($ln['amount']??0),2);$lbl=(string)($ln['label']??'');if(($ln['k']??'')==='quote')$lbl.=' — cijena po dogovoru';$items[]=[$lbl,1,'kom',$amt,0,$amt];$sub+=$amt;}
   $tax=PUB_VAT;$taxTotal=round($sub*$tax/100,2);$total=round($sub+$taxTotal,2);
   $notes='Nastalo iz upita '.$iq['ref_no'].'.'.($iq['message']?"\nPitanja kupca: ".$iq['message']:'');
   q('INSERT INTO offers(offer_no,tenant_id,customer_name,customer_address,customer_jib,customer_pdv,status,valid_until,notes,subtotal,discount_total,tax_rate,tax_total,total,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[next_offer_no(),null,$iq['company_name'],(string)$iq['city'],(string)$iq['jib'],(string)$iq['pdv'],'DRAFT',date('Y-m-d',strtotime('+30 days')),$notes,round($sub,2),0,$tax,$taxTotal,$total]);
   $oid=(int)db()->lastInsertId();$ins=db()->prepare('INSERT INTO offer_items(offer_id,description,qty,unit,unit_price,discount_pct,line_total,sort_order) VALUES(?,?,?,?,?,?,?,?)');foreach($items as $i=>$it)$ins->execute(array_merge([$oid],$it,[$i]));
   q("UPDATE inquiries SET offer_id=?,status=IF(status='NEW','IN_PROGRESS',status),updated_at=NOW() WHERE id=?",[$oid,$id]);
   audit('INQUIRY_TO_OFFER','inquiry',$id,['offer'=>$oid]);header('Location: ?page=offer&id='.$oid.'&saved=1');exit;
  }
  if($act==='save_price_package'){$id=(int)($_POST['id']??0);$v=[trim($_POST['code']),trim($_POST['name']),trim($_POST['description']??''),(float)$_POST['implementation_price'],(float)$_POST['monthly_price'],(float)$_POST['semiannual_price'],(float)$_POST['annual_price'],(int)$_POST['support_minutes'],isset($_POST['active'])?1:0,(int)($_POST['sort_order']??0)];if($id)q('UPDATE price_packages SET code=?,name=?,description=?,implementation_price=?,monthly_price=?,semiannual_price=?,annual_price=?,support_minutes=?,active=?,sort_order=?,updated_at=NOW() WHERE id=?',array_merge($v,[$id]));else{q('INSERT INTO price_packages(code,name,description,implementation_price,monthly_price,semiannual_price,annual_price,support_minutes,active,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',$v);$id=(int)db()->lastInsertId();}audit('PRICE_PACKAGE_SAVE','price_package',$id);header('Location: ?page=pricing&saved=1');exit;}
  if($act==='save_service'){$id=(int)($_POST['id']??0);$v=[trim($_POST['code']),trim($_POST['name']),trim($_POST['description']??''),trim($_POST['unit']??'sat'),(float)$_POST['price'],isset($_POST['active'])?1:0,(int)($_POST['sort_order']??0)];if($id)q('UPDATE service_catalog SET code=?,name=?,description=?,unit=?,price=?,active=?,sort_order=?,updated_at=NOW() WHERE id=?',array_merge($v,[$id]));else{q('INSERT INTO service_catalog(code,name,description,unit,price,active,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,NOW(),NOW())',$v);$id=(int)db()->lastInsertId();}audit('SERVICE_SAVE','service',$id);header('Location: ?page=pricing&saved=1');exit;}
  if($act==='save_commercial_module'){$id=(int)($_POST['id']??0);$v=[trim($_POST['code']),trim($_POST['module_key']),trim($_POST['name']),trim($_POST['description']??''),(float)$_POST['implementation_price'],(float)$_POST['monthly_price'],(float)$_POST['annual_price'],(float)$_POST['partner_commission_pct'],(float)$_POST['referral_bonus'],isset($_POST['active'])?1:0,(int)($_POST['sort_order']??0)];if($id)q('UPDATE commercial_modules SET code=?,module_key=?,name=?,description=?,implementation_price=?,monthly_price=?,annual_price=?,partner_commission_pct=?,referral_bonus=?,active=?,sort_order=?,updated_at=NOW() WHERE id=?',array_merge($v,[$id]));else{q('INSERT INTO commercial_modules(code,module_key,name,description,implementation_price,monthly_price,annual_price,partner_commission_pct,referral_bonus,active,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',$v);$id=(int)db()->lastInsertId();}audit('COMMERCIAL_MODULE_SAVE','commercial_module',$id);header('Location: ?page=pricing&saved=1#accountant-module');exit;}
  if($act==='save_accountant_partner'){$id=(int)($_POST['id']??0);$v=[trim($_POST['name']),trim($_POST['company_name']??''),trim($_POST['email']??''),trim($_POST['phone']??''),(float)($_POST['commission_pct']??20),isset($_POST['active'])?1:0,trim($_POST['notes']??'')];if($id)q('UPDATE accountant_partners SET name=?,company_name=?,email=?,phone=?,commission_pct=?,active=?,notes=?,updated_at=NOW() WHERE id=?',array_merge($v,[$id]));else{q('INSERT INTO accountant_partners(name,company_name,email,phone,commission_pct,active,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,NOW(),NOW())',$v);$id=(int)db()->lastInsertId();}audit('ACCOUNTANT_PARTNER_SAVE','accountant_partner',$id);header('Location: ?page=accountants&saved=partner');exit;}
  if($act==='save_accountant_referral'){$mid=(int)($_POST['commercial_module_id']??0);$m=q('SELECT * FROM commercial_modules WHERE id=?',[$mid])->fetch();if(!$m)throw new RuntimeException('Komercijalni modul nije pronađen.');$pid=(int)($_POST['accountant_partner_id']??0);$partner=q('SELECT * FROM accountant_partners WHERE id=?',[$pid])->fetch();if(!$partner)throw new RuntimeException('Knjigovođa/partner nije pronađen.');$cycle=in_array($_POST['billing_cycle']??'MONTHLY',['MONTHLY','ANNUAL'],true)?$_POST['billing_cycle']:'MONTHLY';$amount=(float)($_POST['module_net_amount']??0);if($amount<=0)$amount=$cycle==='ANNUAL'?(float)$m['annual_price']:(float)$m['monthly_price'];$pct=(float)($partner['commission_pct']?:$m['partner_commission_pct']);$status=in_array($_POST['status']??'LEAD',['LEAD','ACTIVATED','PAID','CANCELLED'],true)?$_POST['status']:'LEAD';$commission=round($amount*$pct/100,2);$bonus=in_array($status,['ACTIVATED','PAID'],true)?(float)$m['referral_bonus']:0;$paidAt=$status==='PAID'?date('Y-m-d H:i:s'):null;q('INSERT INTO accountant_referrals(accountant_partner_id,tenant_id,commercial_module_id,customer_name,status,billing_cycle,module_net_amount,commission_pct,commission_amount,referral_bonus_amount,paid_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[$pid,($_POST['tenant_id']??'')!==''?(int)$_POST['tenant_id']:null,$mid,trim($_POST['customer_name']),$status,$cycle,$amount,$pct,$commission,$bonus,$paidAt]);$id=(int)db()->lastInsertId();audit('ACCOUNTANT_REFERRAL_SAVE','accountant_referral',$id,['status'=>$status,'commission'=>$commission,'bonus'=>$bonus]);header('Location: ?page=accountants&saved=referral');exit;}
  if($act==='save_offer'){$id=(int)($_POST['id']??0);$tid=(int)($_POST['tenant_id']??0);$tid=$tid?:null;$offerNo=trim($_POST['offer_no']??'')?:next_offer_no();$tax=(float)($_POST['tax_rate']??17);$descs=(array)($_POST['item_description']??[]);$qtys=(array)($_POST['item_qty']??[]);$units=(array)($_POST['item_unit']??[]);$prices=(array)($_POST['item_price']??[]);$discounts=(array)($_POST['item_discount']??[]);$items=[];$sub=0;$discTotal=0;foreach($descs as $i=>$d){$d=trim((string)$d);if($d==='')continue;$qty=max(0,(float)($qtys[$i]??1));$price=max(0,(float)($prices[$i]??0));$disc=min(100,max(0,(float)($discounts[$i]??0)));$gross=$qty*$price;$line=$gross*(1-$disc/100);$sub+=$gross;$discTotal+=($gross-$line);$items[]=[$d,$qty,trim((string)($units[$i]??'kom'))?:'kom',$price,$disc,$line];}$net=$sub-$discTotal;$taxTotal=$net*$tax/100;$total=$net+$taxTotal;$vals=[$offerNo,$tid,trim($_POST['customer_name']),trim($_POST['customer_address']??''),trim($_POST['customer_jib']??''),trim($_POST['customer_pdv']??''),$_POST['status']??'DRAFT',($_POST['valid_until']??'')?:null,trim($_POST['notes']??''),$sub,$discTotal,$tax,$taxTotal,$total];if($id){q('UPDATE offers SET offer_no=?,tenant_id=?,customer_name=?,customer_address=?,customer_jib=?,customer_pdv=?,status=?,valid_until=?,notes=?,subtotal=?,discount_total=?,tax_rate=?,tax_total=?,total=?,updated_at=NOW() WHERE id=?',array_merge($vals,[$id]));q('DELETE FROM offer_items WHERE offer_id=?',[$id]);}else{q('INSERT INTO offers(offer_no,tenant_id,customer_name,customer_address,customer_jib,customer_pdv,status,valid_until,notes,subtotal,discount_total,tax_rate,tax_total,total,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',$vals);$id=(int)db()->lastInsertId();}$st=db()->prepare('INSERT INTO offer_items(offer_id,description,qty,unit,unit_price,discount_pct,line_total,sort_order) VALUES(?,?,?,?,?,?,?,?)');foreach($items as $i=>$it)$st->execute(array_merge([$id],$it,[$i]));audit('OFFER_SAVE','offer',$id,['offer_no'=>$offerNo,'total'=>$total]);header('Location: ?page=offer&id='.$id.'&saved=1');exit;}
  if($act==='register_version'){$v=trim($_POST['version']);q('INSERT INTO core_versions(version,name,status,notes,created_at) VALUES(?,?,?,?,NOW())',[$v,trim($_POST['name']),'AVAILABLE',trim($_POST['notes'])]);audit('CORE_VERSION_ADD','core');header('Location: ?page=updates');exit;}
  if($act==='agent_health'){$id=(int)$_POST['tenant_id'];$t=q('SELECT * FROM tenants WHERE id=?',[$id])->fetch();if(!$t)throw new RuntimeException('Firma nije pronađena.');$r=agent_request($t,['action'=>'health']);q('UPDATE tenants SET last_health_at=NOW(),last_health_status=?,agent_version=?,installed_version=?,updated_at=NOW() WHERE id=?',['ONLINE',(string)($r['agent_version']??''),(string)($r['app_version']??$t['installed_version']),$id]);audit('AGENT_HEALTH','tenant',$id,$r);header('Location: ?page=updates&health=1');exit;}
  if($act==='upload_package'){try{$pid=save_update_package($_FILES['package']??[]);$pr=package_row($pid);$ver=(string)$pr['version'];$name=(string)$pr['name'];try{q('INSERT INTO core_versions(version,name,status,package_file,checksum,notes,created_at) VALUES(?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name),status=VALUES(status),package_file=VALUES(package_file),checksum=VALUES(checksum),notes=VALUES(notes)',[$ver,$name,'AVAILABLE',(string)$pid,$pr['checksum'],(string)($pr['notes']??'')]);}catch(Throwable $e){}audit('PACKAGE_UPLOAD','update_package',$pid,['version'=>$ver,'theme'=>$pr['theme']??'']);header('Location: ?page=updates&package=1');exit;}catch(Throwable $e){$flash='Upload nije spremljen: '.$e->getMessage();audit('PACKAGE_UPLOAD_FAILED','update_package',null,['error'=>$e->getMessage()]);}}
  if($act==='archive_package'){$pid=(int)$_POST['package_id'];q('UPDATE update_packages SET archived_at=NOW() WHERE id=?',[$pid]);audit('PACKAGE_ARCHIVE','update_package',$pid);header('Location: ?page=updates&archived=1');exit;}
  if($act==='restore_package'){$pid=(int)$_POST['package_id'];q('UPDATE update_packages SET archived_at=NULL WHERE id=?',[$pid]);audit('PACKAGE_RESTORE','update_package',$pid);header('Location: ?page=updates&restored=1');exit;}
  if($act==='delete_package'){$pid=(int)$_POST['package_id'];$pr=package_row($pid);$used=(int)q('SELECT COUNT(*) FROM deployments WHERE to_version=?',[$pr['version']])->fetchColumn();if($used>0)throw new RuntimeException('Paket je korišten u deploymentu i ne može se trajno obrisati. Arhiviraj ga radi očuvanja audit traga.');$path=package_path($pr);if(is_file($path))@unlink($path);q('DELETE FROM update_packages WHERE id=?',[$pid]);audit('PACKAGE_DELETE','update_package',$pid,['version'=>$pr['version']]);header('Location: ?page=updates&deleted=1');exit;}
  if($act==='deploy_package'){$tid=(int)$_POST['tenant_id'];$pid=(int)$_POST['package_id'];$t=q('SELECT * FROM tenants WHERE id=?',[$tid])->fetch();$p=package_row($pid);if(!$t)throw new RuntimeException('Firma nije pronađena.');$r=deploy_package_to_tenant($t,$p);if(!$r['ok'])throw new RuntimeException($r['message']);header('Location: ?page=updates&deployed=1');exit;}
  if($act==='deploy_package_batch'){
   $pid=(int)($_POST['package_id']??0);$p=package_row($pid);$ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['tenant_ids']??[])))));if(!$ids)throw new RuntimeException('Odaberi barem jednu firmu za rollout.');
   q('INSERT INTO update_rollouts(package_id,status,tenant_count,started_by,started_at) VALUES(?,?,?,?,NOW())',[$pid,'RUNNING',count($ids),(string)(user()['email']??'')]);$rid=(int)db()->lastInsertId();$ok=0;$fail=0;
   foreach($ids as $tid){$t=q('SELECT * FROM tenants WHERE id=?',[$tid])->fetch();if(!$t||!package_target_ok($t,$p)){q('INSERT INTO update_rollout_items(rollout_id,tenant_id,status,message,created_at,updated_at) VALUES(?,?,?,?,NOW(),NOW())',[$rid,$tid,'SKIPPED','Firma nije kompatibilna s paketom.']);$fail++;continue;}q('INSERT INTO update_rollout_items(rollout_id,tenant_id,status,created_at,updated_at) VALUES(?,?,?,NOW(),NOW())',[$rid,$tid,'RUNNING']);$ri=(int)db()->lastInsertId();$r=deploy_package_to_tenant($t,$p);q('UPDATE update_rollout_items SET deployment_id=?,status=?,message=?,updated_at=NOW() WHERE id=?',[$r['deployment_id'],$r['ok']?'SUCCESS':'FAILED',$r['message'],$ri]);if($r['ok'])$ok++;else $fail++;}
   q('UPDATE update_rollouts SET status=?,success_count=?,failed_count=?,finished_at=NOW() WHERE id=?',[$fail?'COMPLETED_WITH_ERRORS':'SUCCESS',$ok,$fail,$rid]);audit('ROLLOUT_COMPLETE','update_rollout',$rid,['package'=>$pid,'success'=>$ok,'failed'=>$fail]);header('Location: ?page=updates&rollout='.$rid);exit;
  }
  if($act==='set_package_channel'){$pid=(int)$_POST['package_id'];$ch=in_array($_POST['release_channel']??'',['DRAFT','PILOT','STABLE'],true)?$_POST['release_channel']:'DRAFT';q('UPDATE update_packages SET release_channel=? WHERE id=?',[$ch,$pid]);audit('PACKAGE_CHANNEL','update_package',$pid,['channel'=>$ch]);header('Location: ?page=updates&channel=1');exit;}
  if($act==='cc_root_cleanup'){if(!is_admin())throw new RuntimeException('Samo administrator može čistiti root.');$_SESSION['cc_cleanup_result']=cc_root_cleanup('manual');header('Location: ?page=system&rootclean=1');exit;}
  if($act==='package_cleanup'){if(!is_admin())throw new RuntimeException('Samo administrator može čistiti pakete.');$r=pkg_cleanup_execute((string)($_POST['plan']??''),!empty($_POST['orphans']));header('Location: ?page=updates&cleaned='.count($r['files']).'&freed='.(int)$r['bytes'].'&rows='.(count($r['deleted_rows'])+count($r['archived_rows'])).($r['failed']?'&cleanfail='.count($r['failed']):''));exit;}
  if($act==='rollback_deployment'){$did=(int)$_POST['deployment_id'];$d=q('SELECT d.*,t.agent_url,t.agent_secret,t.installed_version,t.id tenant_real_id FROM deployments d JOIN tenants t ON t.id=d.tenant_id WHERE d.id=?',[$did])->fetch();if(!$d||empty($d['backup_ref']))throw new RuntimeException('Rollback backup nije dostupan.');$r=agent_request($d,['action'=>'rollback','backup_ref'=>$d['backup_ref']],60);q('UPDATE deployments SET status=?,message=CONCAT(COALESCE(message,""),?) WHERE id=?',['ROLLED_BACK',' | Rollback: '.($r['message']??'OK'),$did]);$actualVersion=(string)($r['app_version']??$d['from_version']);q('UPDATE tenants SET installed_version=?,target_version=?,last_health_at=NOW(),last_health_status="ONLINE",updated_at=NOW() WHERE id=?',[$actualVersion,$actualVersion,$d['tenant_real_id']]);audit('ROLLBACK_SUCCESS','deployment',$did);header('Location: ?page=updates&rollback=1');exit;}
 }catch(Throwable $e){$flash=$e->getMessage();}
}
/* v1.8.0: jedinstvena navigacija (ikone), korisnik i odjava uvijek vidljivi — u dnu sidebara i u gornjoj traci. */
function nav_items():array{return [
 ['dashboard',['dashboard'],'Nadzorna ploča','<path d="M3 13h8V3H3zM13 21h8V11h-8zM3 21h8v-6H3zM13 3v6h8V3z"/>'],
 ['tenants',['tenants','tenant'],'Firme','<path d="M3 21h18M5 21V7l7-4 7 4v14M9 9h1M14 9h1M9 13h1M14 13h1M9 17h1M14 17h1"/>'],
 ['modules',['modules'],'Moduli','<path d="M12 2 3 7l9 5 9-5-9-5zM3 17l9 5 9-5M3 12l9 5 9-5"/>'],
 ['updates',['updates'],'Update Center','<path d="M21 12a9 9 0 1 1-3-6.7L21 8M21 3v5h-5"/>'],
 ['pricing',['pricing'],'Cjenik','<path d="M20.6 13.4 13.4 20.6a2 2 0 0 1-2.8 0L3 13V3h10l7.6 7.6a2 2 0 0 1 0 2.8zM7.5 7.5h.01"/>'],
 ['inquiries',['inquiries','inquiry'],'Upiti','<path d="M22 12h-6l-2 3h-4l-2-3H2M5.5 5.1 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.5-6.9A2 2 0 0 0 16.7 4H7.3a2 2 0 0 0-1.8 1.1z"/>'],
 ['offers',['offers','offer'],'Ponude','<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6M8 13h8M8 17h5"/>'],
 ['accountants',['accountants'],'Knjigovođe','<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>'],
 ['audit',['audit'],'Audit','<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10zM9 12l2 2 4-4"/>'],
 ['system',['system'],'Sistem','<path d="M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.8-.3 1.7 1.7 0 0 0-1 1.5V21a2 2 0 1 1-4 0v-.1a1.7 1.7 0 0 0-1.1-1.5 1.7 1.7 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.7 1.7 0 0 0 .3-1.8 1.7 1.7 0 0 0-1.5-1H3a2 2 0 1 1 0-4h.1a1.7 1.7 0 0 0 1.5-1.1 1.7 1.7 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.7 1.7 0 0 0 1.8.3H9a1.7 1.7 0 0 0 1-1.5V3a2 2 0 1 1 4 0v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.7 1.7 0 0 0-.3 1.8V9a1.7 1.7 0 0 0 1.5 1H21a2 2 0 1 1 0 4h-.1a1.7 1.7 0 0 0-1.5 1z"/>'],
];}
function svg_icon(string $paths):string{return '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'.$paths.'</svg>';}
function logout_form(string $class,string $label='Odjava'):string{return '<form method="post" action="?page=logout" class="'.e($class).'"><input type="hidden" name="csrf" value="'.e(csrf()).'"><button type="submit" title="Odjava iz Control Centra">'.svg_icon('<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9"/>').'<span>'.e($label).'</span></button></form>';}
function layout_top(string $title):void{global $page;$u=user()??[];$name=(string)($u['name']??'Administrator');$mail=(string)($u['email']??'');
 header('X-Frame-Options: DENY');header('Referrer-Policy: same-origin');?><!doctype html><html lang="bs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#061a2e"><title><?=e($title)?> · MMC ERP Control Center</title><link rel="stylesheet" href="public/style.css?v=<?=e(cc_version())?>"></head><body class="admin-pro cc-shell">
<aside class="cc-side" id="ccSide"><div class="brand"><span class="brand-mark">MMC</span> <b>ERP</b><small>PLATFORM CONTROL CENTER</small></div>
<nav aria-label="Glavna navigacija"><?php foreach(nav_items() as [$key,$pages,$label,$icon]):$on=in_array($page,$pages,true);?><a class="<?=$on?'on':''?>" href="?page=<?=$key?>" <?=$on?'aria-current="page"':''?>><?=svg_icon($icon)?><span><?=e($label)?></span><?php if($key==='inquiries'&&($nn=inquiry_new_count())>0):?><em class="nav-badge" title="Novi upiti"><?=$nn?></em><?php endif;?></a><?php endforeach;?></nav>
<div class="who"><span class="avatar"><?=e(user_initials($name))?></span><div class="who-text"><b><?=e($name)?></b><small title="<?=e($mail)?>"><?=e($mail)?></small><em><?=e(role_label((string)($u['role']??'')))?></em></div><?=logout_form('logout-side')?></div>
<div class="side-ver">Control Center v<?=e(cc_version())?></div></aside>
<div class="cc-backdrop" id="ccBackdrop" hidden></div>
<main class="content"><header class="cc-top"><button type="button" class="cc-burger" id="ccBurger" aria-label="Izbornik" aria-controls="ccSide" aria-expanded="false"><?=svg_icon('<path d="M3 6h18M3 12h18M3 18h18"/>')?></button><div class="cc-top-title"><h1><?=e($title)?></h1><p>Centralno upravljanje firmama, Core verzijama i modulima</p></div><div class="cc-top-right"><div class="date"><?=date('d.m.Y.')?></div><details class="user-menu"><summary><span class="avatar"><?=e(user_initials($name))?></span><span class="um-name"><?=e($name)?></span></summary><div class="um-pop"><b><?=e($name)?></b><small><?=e($mail)?></small><em><?=e(role_label((string)($u['role']??'')))?></em><?=logout_form('logout-menu','Odjava')?></div></details></div></header><?php global $flash;if(!empty($flash))echo '<div class="alert err">'.e((string)$flash).'</div>';echo cc_root_warning_banner(); }
function layout_bottom():void{?></main><script>(function(){var b=document.getElementById('ccBurger'),s=document.getElementById('ccSide'),k=document.getElementById('ccBackdrop');if(!b||!s)return;function t(o){document.body.classList.toggle('nav-open',o);b.setAttribute('aria-expanded',o);k.hidden=!o;}b.addEventListener('click',function(){t(!document.body.classList.contains('nav-open'));});k.addEventListener('click',function(){t(false);});document.addEventListener('keydown',function(e){if(e.key==='Escape'){t(false);document.querySelectorAll('.user-menu[open]').forEach(function(d){d.open=false;});}});document.addEventListener('click',function(e){document.querySelectorAll('.user-menu[open]').forEach(function(d){if(!d.contains(e.target))d.open=false;});});})();</script></body></html><?php }
if($page==='dashboard'){$cleanRes=cc_root_cleanup_auto();layout_top('Control Center');echo cc_cleanup_notice($cleanRes);
 if(($nq=inquiry_new_count())>0)echo '<div class="alert info inq-alert"><b>'.$nq.' '.($nq===1?'novi upit':'novih upita').'</b> s javnog cjenika čeka odgovor. <a href="?page=inquiries&status=NEW">Otvori upite →</a></div>';
 $ts=q('SELECT * FROM tenants ORDER BY status=\'ACTIVE\' DESC,name')->fetchAll();$profiles=tenant_profiles();
 $active=count(array_filter($ts,fn($t)=>$t['status']==='ACTIVE'));
 $modCount=[];foreach(q('SELECT tenant_id,COUNT(*) n FROM tenant_modules WHERE enabled=1 GROUP BY tenant_id')->fetchAll() as $r)$modCount[(int)$r['tenant_id']]=(int)$r['n'];$mods=array_sum($modCount);
 $agents=count(array_filter($ts,fn($t)=>agent_status_label($t)==='ONLINE'));
 $states=[];foreach($ts as $t)$states[(int)$t['id']]=tenant_update_state($t);
 $pending=count(array_filter($states,fn($x)=>$x['state']==='available'));
 $vers=array_values(array_filter(array_map(fn($t)=>(string)$t['installed_version'],$ts)));usort($vers,'core_version_cmp');$top=$vers?core_vnum((string)end($vers)):'—';
 ?><section class="cc-hero"><div><span class="cc-kicker">MMC ERP PLATFORM · CENTRALNA ADMINISTRACIJA</span><h2>Sve ERP instance pod jednom kontrolom.</h2><p>Pregled firmi, Core verzija, modula, fiskalnih drivera i sigurnih centralnih nadogradnji.</p></div><div class="cc-state"><i></i><div><b>Platforma aktivna</b><small>Control Center v<?=e(cc_version())?></small></div></div></section>
 <section class="kpis kpis-pro"><div><small>FIRME</small><b><?=count($ts)?></b><span><?=$active?> aktivn<?=$active===1?'a':'e'?> · <?=count($profiles)?> profila djelatnosti</span></div><div><small>CORE</small><b><?=e($top)?></b><span><?=$pending?'<a href="?page=updates">'.$pending.' '.($pending===1?'firma čeka':'firme čekaju').' nadogradnju</a>':($ts?'Sve firme su ažurne':'Nema registriranih firmi')?></span></div><div><small>MODULI</small><b><?=$mods?></b><span>Aktivno kroz sve firme</span></div><div><small>UPDATE AGENT</small><b class="<?=$agents===count($ts)&&count($ts)?'agent-on':'agent-off'?>"><?=$agents?>/<?=count($ts)?></b><span><?=$agents===count($ts)&&$ts?'Svi agenti povezani':'Povezani agenti'?></span></div></section>
 <section class="cc-toolbar"><div><h2>ERP instance</h2><p>Sve firme registrirane u centralnoj platformi — nove se ovdje pojavljuju automatski.</p></div><div><a class="btn" href="?page=tenants">Sve firme</a><a class="btn" href="?page=updates">Update Center</a><a class="btn primary" href="?page=tenant">+ Nova firma</a></div></section>
 <?php if(!$ts):?><div class="empty-state panel"><b>Još nema registriranih firmi.</b><p>Dodaj prvu ERP instancu — profil djelatnosti automatski predlaže module, a Update Center joj nudi samo kompatibilne Core pakete.</p><a class="btn primary" href="?page=tenant">+ Nova firma</a></div><?php endif;?>
 <section class="tenant-grid tenant-grid-pro"><?php foreach($ts as $t):$host=parse_url((string)$t['base_url'],PHP_URL_HOST)?:$t['base_url'];$st=$states[(int)$t['id']];$ag=agent_status_label($t);$prof=tenant_app_type($t);?><article class="tenant-card tenant-card-pro status-<?=e(strtolower((string)$t['status']))?>"><div class="tenant-topline"><span class="live-dot"></span><span><?=e(tenant_stage_label((string)$t['status']))?></span><em>Core <?=e($t['installed_version']?:'—')?></em></div><div class="tenant-title"><div><h3><?=e($t['name'])?></h3><p><?=e($profiles[$prof]??$t['industry'])?> · <?=e($t['industry'])?></p></div><?=tenant_status_badge((string)$t['status'])?></div><div class="meta"><span>Domena<b><?=e($host)?></b></span><span>Fiskalni driver<b><?=e($t['fiscal_driver'])?></b></span><span>Aktivni moduli<b><?=$modCount[(int)$t['id']]??0?></b></span><span>Health Agent<b class="<?=$ag==='ONLINE'?'online':'pending'?>"><?=e($ag)?></b></span></div><div class="tenant-health update-<?=e($st['state'])?>"><span><i></i> <?=e($st['label'])?></span><span class="muted"><?=!empty($t['last_health_at'])?'Zadnja provjera: '.e(fmt_dt($t['last_health_at'])):'Health provjera čeka agent'?></span></div><div class="actions"><a class="btn primary-soft" target="_blank" rel="noopener" href="<?=e($t['base_url'])?>">Otvori ERP ↗</a><a class="btn" href="?page=tenant&id=<?=$t['id']?>">Postavke</a><a class="btn" href="?page=modules&tenant=<?=$t['id']?>">Moduli</a><a class="btn<?=$st['state']==='available'?' primary':''?>" href="?page=updates&tenant=<?=$t['id']?>">Nadogradnje</a></div></article><?php endforeach;?></section><section class="cc-roadmap"><div><b>Health & Update Agent</b><span>Potpisana veza → backup datoteka → deployment → health check → rollback</span></div><a class="btn" href="?page=updates">Otvori Update Center</a></section><?php layout_bottom();exit;}
if($page==='tenants'){layout_top('Firme');$ts=q('SELECT * FROM tenants ORDER BY name')->fetchAll();$profiles=tenant_profiles();?><div class="section-head"><div><h2>Registrirane instance</h2><p><?=count($ts)?> firmi · profil određuje module i kompatibilne Core pakete</p></div><a class="btn primary" href="?page=tenant">+ Nova firma</a></div><?php if(!$ts):?><div class="empty-state panel">Nema registriranih firmi. <a href="?page=tenant">Dodaj prvu firmu</a>.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Firma</th><th>Profil</th><th>Domena</th><th>Core</th><th>Nadogradnja</th><th>Agent</th><th>Driver</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($ts as $t):$st=tenant_update_state($t);?><tr><td><b><?=e($t['name'])?></b><small class="cell-sub"><?=e($t['industry'])?></small></td><td><?=e($profiles[tenant_app_type($t)]??'—')?></td><td><a href="<?=e($t['base_url'])?>" target="_blank" rel="noopener"><?=e(parse_url((string)$t['base_url'],PHP_URL_HOST)?:$t['base_url'])?></a></td><td><?=e($t['installed_version']?:'—')?></td><td><?=badge($st['label'],$st['state']==='current'?'ok':'warn')?></td><td><?=e(agent_status_label($t))?></td><td><?=e($t['fiscal_driver'])?></td><td><?=tenant_status_badge((string)$t['status'])?></td><td class="nowrap"><a class="btn small" href="?page=tenant&id=<?=$t['id']?>">Uredi</a> <a class="btn small" href="?page=updates&tenant=<?=$t['id']?>">Nadogradnje</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;layout_bottom();exit;}
if($page==='tenant'){
 $id=(int)($_GET['id']??0);
 $t=$id?q('SELECT * FROM tenants WHERE id=?',[$id])->fetch():null;
 $preset=$_GET['preset']??'';
 $profile=$t?tenant_app_type($t):'retail';
 $mods=$id?tenant_modules($id):tenant_profile_modules($profile);
 layout_top($t?'Postavke firme':'Nova firma');
 if(isset($_GET['saved']))echo '<div class="alert ok">Promjene spremljene.</div>';?>
 <form method="post" class="panel form-grid" id="tenantForm130">
  <input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_tenant"><input type="hidden" name="id" value="<?=$id?>">
  <label>Naziv firme<input name="name" value="<?=e($t['name']??'')?>" required></label>
  <label>Slug<input name="slug" value="<?=e($t['slug']??'')?>" required pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="npr. optika-isic"><small>Jedinstveni ključ firme za pakete i API.</small></label>
  <label>Profil djelatnosti<select name="profile" id="tenantProfile">
   <?php foreach(tenant_profiles() as $pk=>$pl):?><option value="<?=e($pk)?>" <?=$profile===$pk?'selected':''?>><?=e($pl)?></option><?php endforeach;?>
  </select><small>Profil automatski predlaže module; ručno ih možeš promijeniti.</small></label>
  <label>Djelatnost<input name="industry" value="<?=e($t['industry']??'')?>" required placeholder="npr. Trgovina mješovite robe"></label>
  <label>URL instance<input type="url" name="base_url" value="<?=e($t['base_url']??'https://')?>" required></label>
  <label>Naziv baze (evidencija)<input name="db_name" value="<?=e($t['db_name']??'')?>"></label>
  <label>DB korisnik (bez lozinke)<input name="db_user" value="<?=e($t['db_user']??'')?>"></label>
  <label>Fiskalni driver<select name="fiscal_driver"><?php foreach(['NONE','TRING','DATECS'] as $x):?><option <?=$x===($t['fiscal_driver']??'NONE')?'selected':''?>><?=$x?></option><?php endforeach;?></select></label>
  <label>JIB<input name="jib" value="<?=e($t['jib']??'')?>"></label>
  <label>PDV<input name="pdv" value="<?=e($t['pdv']??'')?>"></label>
  <label class="wide">Adresa<input name="address" value="<?=e($t['address']??'')?>"></label>
  <label>Mjesto<input name="city" value="<?=e($t['city']??'')?>"></label>
  <label>Poštanski broj<input name="postal_code" value="<?=e($t['postal_code']??'')?>"></label>
  <label>Država<input name="country" value="<?=e($t['country']??'Bosna i Hercegovina')?>"></label>
  <label>Instalirani Core<input name="installed_version" value="<?=e($t['installed_version']??'')?>" placeholder="npr. 5.12.1 — agent je javlja automatski"></label>
  <label>Ciljni Core<input name="target_version" value="<?=e($t['target_version']??'')?>" placeholder="npr. 5.12.2"></label>
  <label>Status<select name="status"><?php foreach(tenant_statuses() as $x=>$xl):?><option value="<?=$x?>" <?=$x===($t['status']??'ACTIVE')?'selected':''?>><?=e($xl)?></option><?php endforeach;?></select></label>
  <label class="wide">Update Agent URL<input type="url" name="agent_url" value="<?=e($t['agent_url']??(($t['base_url']??'').'/mmc-agent.php'))?>" placeholder="https://firma.tld/mmc-agent.php"></label>
  <label class="wide">Update Agent tajni ključ<input name="agent_secret" value="" autocomplete="new-password" placeholder="<?=!empty($t['agent_secret'])?'spremljen (…'.e(substr(hash('sha256',(string)$t['agent_secret']),0,6)).') — ostavi prazno da ostane isti; „-“ briše ključ':'kopirati iz mmc-agent.config.php'?>"></label>
  <fieldset class="wide"><legend>Aktivni moduli</legend><div class="checks" id="tenantModules"><?php foreach(modules_catalog() as $k=>$n):?><label><input type="checkbox" name="modules[]" value="<?=$k?>" <?=in_array($k,$mods)?'checked':''?> <?=$k==='core'?'disabled':''?>> <?=e($n)?></label><?php endforeach;?><input type="hidden" name="modules[]" value="core"></div><small>Za brže slaganje paketa koristi novi <a href="?page=modules&tenant=<?=$id?>">Module Center</a>.</small></fieldset>
  <div class="wide"><button class="btn primary">Spremi firmu</button><?php if($t):?> <a target="_blank" class="btn" href="<?=e($t['base_url'])?>">Otvori ERP</a><?php endif;?></div>
 </form>
 <script>
 (function(){
   const p=document.getElementById('tenantProfile'), box=document.getElementById('tenantModules');
   if(!p||!box)return;
   const presets=<?=json_encode(array_map('tenant_profile_modules',array_combine(array_keys(tenant_profiles()),array_keys(tenant_profiles()))),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;
   p.addEventListener('change',()=>{
     const set=new Set(presets[p.value]||presets.retail);
     box.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=set.has(x.value));
   });
 })();
 </script>
 <script>document.querySelectorAll('.select-all-compatible').forEach(function(b){b.addEventListener('click',function(){var f=b.closest('.rollout-form'),c=[...f.querySelectorAll('input[name="tenant_ids[]"]')],all=c.length&&c.every(x=>x.checked);c.forEach(x=>x.checked=!all);b.textContent=all?'Sve':'Ništa';});});</script>
 <?php layout_bottom();exit;
}
if($page==='modules'){
 layout_top('Module Center');$ts=q('SELECT * FROM tenants ORDER BY name')->fetchAll();$defs=module_definitions();$groups=module_grouped();$commercial=[];foreach(q('SELECT * FROM commercial_modules WHERE active=1 ORDER BY sort_order,id')->fetchAll() as $cm)$commercial[$cm['module_key']]=$cm;$selected=(int)($_GET['tenant']??($ts[0]['id']??0));$tenant=$selected?q('SELECT * FROM tenants WHERE id=?',[$selected])->fetch():null;$active=$tenant?tenant_modules($selected):[];$presets=module_presets();if(isset($_GET['saved']))echo '<div class="alert ok">Moduli za odabranu firmu su spremljeni. Ovisnosti su automatski uključene.</div>'; ?>
 <section class="module-center-hero"><div><span class="cc-kicker">MMC ERP · ENTITLEMENTS & MODULARNA AKTIVACIJA</span><h2>Jedan centar za sve module i sve klijente.</h2><p>Odaberi firmu, primijeni paket ili ručno uključi module. Core i potrebne ovisnosti sustav uključuje automatski.</p></div><div class="module-center-count"><b><?=count($defs)?></b><span>modula u katalogu</span></div></section>
 <form method="get" class="module-tenant-picker"><input type="hidden" name="page" value="modules"><label>Klijent / ERP firma<select name="tenant" onchange="this.form.submit()"><?php foreach($ts as $t):?><option value="<?=$t['id']?>" <?=$selected===(int)$t['id']?'selected':''?>><?=e($t['name'])?> · <?=e(tenant_app_type($t))?></option><?php endforeach;?></select></label><?php if($tenant):?><div class="module-tenant-summary"><span><?=badge($tenant['status'],$tenant['status']==='ACTIVE'?'ok':'warn')?></span><b><?=e(parse_url($tenant['base_url'],PHP_URL_HOST)?:$tenant['base_url'])?></b><small><?=count($active)?> aktivnih modula</small></div><?php endif;?></form>
 <?php if($tenant):?><form method="post" class="module-center-form" id="moduleCenterForm"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_module_center"><input type="hidden" name="tenant_id" value="<?=$selected?>">
 <section class="module-presets"><div><b>Brzi paketi</b><small>Polazište koje nakon toga možeš ručno doraditi.</small></div><div class="preset-actions"><?php foreach($presets as $pk=>$pm):?><button type="button" class="btn preset-btn" data-modules='<?=e(json_encode($pm))?>'><?=$pk?></button><?php endforeach;?><button type="button" class="btn" id="clearOptional">Samo Core</button></div></section>
 <div class="module-groups"><?php foreach($groups as $group=>$items):?><section class="module-group"><div class="module-group-head"><h3><?=e($group)?></h3><span><?=count($items)?> modula</span></div><div class="module-card-grid"><?php foreach($items as $k=>$d):$isOn=in_array($k,$active,true);$cm=$commercial[$k]??null;?><label class="module-card <?=$isOn?'is-active':''?>"><input type="checkbox" name="modules[]" value="<?=$k?>" <?=$isOn?'checked':''?> <?=$k==='core'?'disabled':''?>><div class="module-switch"><i></i></div><div class="module-copy"><div class="module-title"><b><?=e($d['name'])?></b><?php if(!empty($d['commercial'])):?><span class="module-addon">ADD-ON</span><?php endif;?></div><p><?=e($d['description'])?></p><small><?php if(!empty($d['depends'])):?>Treba: <?=e(implode(', ',array_map(fn($x)=>$defs[$x]['name']??$x,$d['depends'])))?><?php else:?>Samostalan modul<?php endif;?></small><?php if($cm):?><strong><?=number_format((float)$cm['monthly_price'],2,',','.')?> KM/mj.</strong><?php endif;?></div></label><?php endforeach;?></div></section><?php endforeach;?></div><input type="hidden" name="modules[]" value="core">
 <div class="module-savebar"><div><b><?=e($tenant['name'])?></b><span>Spremanjem mijenjaš pravo korištenja modula za ovu ERP instancu.</span></div><button class="btn primary">Spremi aktivne module</button></div></form>
 <script>(function(){const form=document.getElementById('moduleCenterForm');if(!form)return;const boxes=[...form.querySelectorAll('input[type=checkbox][name="modules[]"]')];function sync(){form.querySelectorAll('.module-card').forEach(c=>c.classList.toggle('is-active',!!c.querySelector('input[type=checkbox]')?.checked));}document.querySelectorAll('.preset-btn').forEach(b=>b.addEventListener('click',()=>{let list=[];try{list=JSON.parse(b.dataset.modules||'[]')}catch(e){}const set=new Set(list);boxes.forEach(x=>x.checked=x.value==='core'||set.has(x.value));sync();}));document.getElementById('clearOptional')?.addEventListener('click',()=>{boxes.forEach(x=>x.checked=x.value==='core');sync();});boxes.forEach(x=>x.addEventListener('change',sync));sync();})();</script><?php else:?><div class="empty-state">Prvo registriraj ERP firmu.</div><?php endif;layout_bottom();exit;
}
if($page==='pricing'){
 $packs=q('SELECT * FROM price_packages ORDER BY sort_order,id')->fetchAll();$services=q('SELECT * FROM service_catalog ORDER BY sort_order,id')->fetchAll();$addons=q('SELECT * FROM commercial_modules ORDER BY sort_order,id')->fetchAll();
 if(($_GET['mode']??'')==='presentation'){?><!doctype html><html lang="bs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>MMC ERP · Cjenik</title><link rel="stylesheet" href="public/style.css"></head><body class="presentation-body"><div class="presentation-shell"><header class="presentation-head"><div><span class="cc-kicker">MMC ERP PLATFORM</span><h1>Paketi i opcije</h1><p>Jasan pregled za prezentaciju klijentu.</p></div><div class="presentation-actions"><a class="btn" href="?page=pricing">Administracija</a><a class="btn primary" href="?page=offer">Kreiraj ponudu</a></div></header><section class="showcase-grid"><?php foreach($packs as $p):if(!$p['active'])continue;?><article class="showcase-card"><div class="showcase-title"><span><?=e($p['code'])?></span><h2><?=e($p['name'])?></h2></div><p><?=e($p['description']??'')?></p><div class="showcase-price"><small>Implementacija</small><b><?=money_bam((float)$p['implementation_price'])?></b></div><div class="showcase-sub"><div><small>Mjesečno</small><b><?=money_bam((float)$p['monthly_price'])?></b></div><div><small>6 mjeseci</small><b><?=money_bam((float)$p['semiannual_price'])?></b></div><div><small>12 mjeseci</small><b><?=money_bam((float)$p['annual_price'])?></b></div></div><div class="showcase-note">Uključeno <?=e((string)$p['support_minutes'])?> min podrške mjesečno</div></article><?php endforeach;?></section><?php if($addons):?><section class="showcase-addon"><div><span class="cc-kicker">DODATNI MODUL</span><h2>Centar knjigovođe</h2><p>Odvojena aktivacija za suradnju firme i knjigovođe: pregled računovodstvenih podataka, KUF/KIF i PDV priprema, razmjena dokumenata, kontrole i korekcije.</p></div><?php foreach($addons as $m):if(!$m['active'])continue;?><div class="addon-price"><small><?=e($m['name'])?></small><b><?=money_bam((float)$m['monthly_price'])?> <em>/ mj.</em></b><span><?=money_bam((float)$m['annual_price'])?> / 12 mj.</span></div><?php endforeach;?></section><?php endif;?><footer class="presentation-foot"><span>Cijene su bez PDV-a.</span><b><?=date('d.m.Y.')?></b></footer></div></body></html><?php exit;}
 layout_top('Cjenik');if(isset($_GET['saved']))echo '<div class="alert ok">Cjenik je spremljen.</div>';?>
 <section class="cc-toolbar pricing-toolbar"><div><h2>MMC ERP Cloud paketi</h2><p>Centralni komercijalni cjenik za nove i postojeće ERP klijente.</p></div><div><a class="btn" href="<?=e(pub_site_url())?>/cjenik" target="_blank" rel="noopener">Javna stranica /cjenik ↗</a> <a class="btn" href="?page=inquiries">Upiti</a> <a class="btn presentation-btn" href="?page=pricing&mode=presentation">▣ Prezentacijski prikaz</a><a class="btn primary" href="?page=offer">Kreiraj ponudu</a></div></section>
 <section class="price-grid"><?php foreach($packs as $p):?><form method="post" class="panel price-card"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_price_package"><input type="hidden" name="id" value="<?=$p['id']?>"><div class="price-head"><input name="code" value="<?=e($p['code'])?>" required><input name="name" value="<?=e($p['name'])?>" required></div><textarea name="description" rows="3"><?=e($p['description']??'')?></textarea><div class="price-fields"><label>Implementacija<input type="number" step="0.01" name="implementation_price" value="<?=$p['implementation_price']?>"></label><label>Mjesečno<input type="number" step="0.01" name="monthly_price" value="<?=$p['monthly_price']?>"></label><label>6 mjeseci<input type="number" step="0.01" name="semiannual_price" value="<?=$p['semiannual_price']?>"></label><label>12 mjeseci<input type="number" step="0.01" name="annual_price" value="<?=$p['annual_price']?>"></label><label>Podrška min/mj.<input type="number" name="support_minutes" value="<?=$p['support_minutes']?>"></label><label>Redoslijed<input type="number" name="sort_order" value="<?=$p['sort_order']?>"></label></div><label class="checkline"><input type="checkbox" name="active" <?=$p['active']?'checked':''?>> Aktivan paket</label><button class="btn primary">Spremi paket</button></form><?php endforeach;?></section>
 <section class="panel accountant-module-panel" id="accountant-module"><div class="section-head"><div><span class="cc-kicker">ODVOJENA AKTIVACIJA I NAPLATA</span><h2>Modul za knjigovođe</h2><p>Centar knjigovođe se uključuje neovisno o START / BUSINESS / PRO paketu.</p></div><a class="btn" href="?page=accountants">Partner program →</a></div><?php foreach($addons as $m):?><form method="post" class="accountant-module-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_commercial_module"><input type="hidden" name="id" value="<?=$m['id']?>"><div class="form-grid"><label>Šifra<input name="code" value="<?=e($m['code'])?>" required></label><label>ERP modul<input name="module_key" value="<?=e($m['module_key'])?>" required></label><label class="wide">Naziv<input name="name" value="<?=e($m['name'])?>" required></label><label class="wide">Opis<textarea name="description" rows="3"><?=e($m['description']??'')?></textarea></label><label>Aktivacija / implementacija<input type="number" step="0.01" name="implementation_price" value="<?=$m['implementation_price']?>"></label><label>Mjesečno<input type="number" step="0.01" name="monthly_price" value="<?=$m['monthly_price']?>"></label><label>12 mjeseci<input type="number" step="0.01" name="annual_price" value="<?=$m['annual_price']?>"></label><label>Provizija knjigovođi %<input type="number" step="0.01" name="partner_commission_pct" value="<?=$m['partner_commission_pct']?>"></label><label>Bonus za novog klijenta KM<input type="number" step="0.01" name="referral_bonus" value="<?=$m['referral_bonus']?>"></label><label>Redoslijed<input type="number" name="sort_order" value="<?=$m['sort_order']?>"></label></div><label class="checkline"><input type="checkbox" name="active" <?=$m['active']?'checked':''?>> Modul aktivan za prodaju</label><button class="btn primary">Spremi modul</button></form><?php endforeach;?></section>
 <section class="panel"><div class="section-head"><h2>Dodatne usluge</h2></div><div class="table-wrap service-table"><table><thead><tr><th>Šifra</th><th>Usluga</th><th>Jedinica</th><th>Cijena bez PDV</th><th>Status</th></tr></thead><tbody><?php foreach($services as $s):?><tr><td><?=e($s['code'])?></td><td><b><?=e($s['name'])?></b><small class="cell-sub"><?=e($s['description']??'')?></small></td><td><?=e($s['unit'])?></td><td><?=money_bam((float)$s['price'])?></td><td><?=badge($s['active']?'AKTIVNO':'NEAKTIVNO',$s['active']?'ok':'warn')?></td></tr><?php endforeach;?></tbody></table></div></section>
 <?php layout_bottom();exit;
}
if($page==='accountants'){
 layout_top('Knjigovođe');$partners=q('SELECT * FROM accountant_partners ORDER BY active DESC,name')->fetchAll();$refs=q('SELECT r.*,p.name partner_name,p.company_name,m.name module_name,t.name tenant_name FROM accountant_referrals r JOIN accountant_partners p ON p.id=r.accountant_partner_id JOIN commercial_modules m ON m.id=r.commercial_module_id LEFT JOIN tenants t ON t.id=r.tenant_id ORDER BY r.id DESC LIMIT 100')->fetchAll();$mods=q('SELECT * FROM commercial_modules WHERE active=1 ORDER BY sort_order,id')->fetchAll();$ts=q('SELECT * FROM tenants ORDER BY name')->fetchAll();if(isset($_GET['saved']))echo '<div class="alert ok">Partner program je spremljen.</div>';
 $projected=array_sum(array_map(fn($r)=>(float)$r['commission_amount']+(float)$r['referral_bonus_amount'],$refs));$paid=array_sum(array_map(fn($r)=>$r['status']==='PAID'?((float)$r['commission_amount']+(float)$r['referral_bonus_amount']):0,$refs));?>
 <section class="cc-hero accountant-hero"><div><span class="cc-kicker">MMC ERP · ACCOUNTANT PARTNER PROGRAM</span><h2>Knjigovođa postaje partner, ne samo korisnik izvoza.</h2><p>Odvojeno naplaćen modul njihovim klijentima, provizija na modul i jednokratni bonus kada dovedu novog ERP klijenta.</p></div><div class="cc-state"><div><b><?=count($partners)?> partnera</b><small><?=money_bam($paid)?> evidentirano kao isplaćeno</small></div></div></section>
 <section class="kpis kpis-pro"><div><small>PARTNERI</small><b><?=count($partners)?></b><span>Registrirane knjigovođe</span></div><div><small>PREPORUKE</small><b><?=count($refs)?></b><span>Lead / aktivacija / naplata</span></div><div><small>OBVEZE PARTNERIMA</small><b><?=money_bam($projected)?></b><span>Provizije + bonusi ukupno</span></div><div><small>ISPLAĆENO</small><b><?=money_bam($paid)?></b><span>Evidentirano kao PAID</span></div></section>
 <section class="partner-grid"><form method="post" class="panel"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_accountant_partner"><h2>Nova knjigovođa / partner</h2><div class="form-grid"><label>Ime i prezime<input name="name" required></label><label>Knjigovodstveni servis<input name="company_name"></label><label>Email<input type="email" name="email"></label><label>Telefon<input name="phone"></label><label>Provizija na modul %<input type="number" step="0.01" name="commission_pct" value="20"></label><label class="checkline partner-active"><input type="checkbox" name="active" checked> Aktivan partner</label><label class="wide">Napomena<textarea name="notes" rows="3" placeholder="Područje, specifičnosti, dogovorene korekcije i savjeti..."></textarea></label></div><button class="btn primary">Spremi partnera</button></form>
 <form method="post" class="panel"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_accountant_referral"><h2>Klijent / preporuka</h2><div class="form-grid"><label>Knjigovođa<select name="accountant_partner_id" required><option value="">Odaberi...</option><?php foreach($partners as $p):if(!$p['active'])continue;?><option value="<?=$p['id']?>"><?=e($p['name'])?><?=($p['company_name']??'')?' · '.e($p['company_name']):''?></option><?php endforeach;?></select></label><label>Modul<select name="commercial_module_id" required><?php foreach($mods as $m):?><option value="<?=$m['id']?>"><?=e($m['name'])?></option><?php endforeach;?></select></label><label class="wide">Klijent<input name="customer_name" required></label><label>Postojeći ERP tenant<select name="tenant_id"><option value="">— novi / još nije tenant —</option><?php foreach($ts as $t):?><option value="<?=$t['id']?>"><?=e($t['name'])?></option><?php endforeach;?></select></label><label>Status<select name="status"><option value="LEAD">Lead</option><option value="ACTIVATED">Aktiviran modul</option><option value="PAID">Naplata evidentirana</option><option value="CANCELLED">Otkazano</option></select></label><label>Obračun<select name="billing_cycle"><option value="MONTHLY">Mjesečno</option><option value="ANNUAL">Godišnje</option></select></label><label>Neto iznos modula<input type="number" step="0.01" name="module_net_amount" placeholder="0 = uzmi cijenu iz cjenika"></label></div><button class="btn primary">Evidentiraj preporuku</button></form></section>
 <section class="panel"><div class="section-head"><div><h2>Partneri</h2><p>Provizija je individualno podesiva po knjigovođi.</p></div></div><div class="table-wrap"><table><thead><tr><th>Partner</th><th>Kontakt</th><th>Provizija</th><th>Status</th></tr></thead><tbody><?php foreach($partners as $p):?><tr><td><b><?=e($p['name'])?></b><small class="cell-sub"><?=e($p['company_name']??'')?></small></td><td><?=e($p['email']??'')?><small class="cell-sub"><?=e($p['phone']??'')?></small></td><td><?=number_format((float)$p['commission_pct'],2,',','.')?>%</td><td><?=badge($p['active']?'AKTIVAN':'NEAKTIVAN',$p['active']?'ok':'warn')?></td></tr><?php endforeach;?></tbody></table></div></section>
 <section class="panel"><div class="section-head"><div><h2>Preporuke i obračun</h2><p>Bonus se dodaje nakon aktivacije, a status PAID označava evidentiranu naplatu/isplatu.</p></div></div><div class="table-wrap"><table><thead><tr><th>Klijent</th><th>Knjigovođa</th><th>Modul</th><th>Status</th><th>Neto</th><th>Provizija</th><th>Bonus</th><th>Ukupno partneru</th></tr></thead><tbody><?php foreach($refs as $r):?><tr><td><b><?=e($r['customer_name'])?></b><small class="cell-sub"><?=e($r['tenant_name']??'')?></small></td><td><?=e($r['partner_name'])?></td><td><?=e($r['module_name'])?><small class="cell-sub"><?=e($r['billing_cycle'])?></small></td><td><?=badge($r['status'],$r['status']==='PAID'?'ok':($r['status']==='CANCELLED'?'warn':'info'))?></td><td><?=money_bam((float)$r['module_net_amount'])?></td><td><?=money_bam((float)$r['commission_amount'])?><small class="cell-sub"><?=number_format((float)$r['commission_pct'],2,',','.')?>%</small></td><td><?=money_bam((float)$r['referral_bonus_amount'])?></td><td><b><?=money_bam((float)$r['commission_amount']+(float)$r['referral_bonus_amount'])?></b></td></tr><?php endforeach;?></tbody></table></div></section>
 <?php layout_bottom();exit;
}
if($page==='offers'){
 layout_top('Ponude');$rows=q('SELECT o.*,t.name tenant_name FROM offers o LEFT JOIN tenants t ON t.id=o.tenant_id ORDER BY o.id DESC')->fetchAll();?>
 <section class="cc-toolbar"><div><h2>Komercijalne ponude</h2><p>Ponude za implementaciju, licence, hosting, održavanje i dodatne usluge.</p></div><a class="btn" href="?page=pricing">Cjenik</a> <a class="btn primary" href="?page=offer">+ Nova ponuda</a></section>
 <div class="table-wrap"><table><thead><tr><th>Broj</th><th>Kupac / firma</th><th>Status</th><th>Vrijedi do</th><th>Ukupno s PDV</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?=e($r['offer_no'])?></b></td><td><?=e($r['customer_name'])?><small class="cell-sub"><?=e($r['tenant_name']??'')?></small></td><td><?=badge($r['status'],$r['status']==='ACCEPTED'?'ok':($r['status']==='DRAFT'?'info':'warn'))?></td><td><?=e($r['valid_until']??'—')?></td><td><b><?=money_bam((float)$r['total'])?></b></td><td><a class="btn small" href="?page=offer&id=<?=$r['id']?>">Otvori</a></td></tr><?php endforeach;?></tbody></table></div>
 <?php layout_bottom();exit;
}
if($page==='offer'){
 $id=(int)($_GET['id']??0);$o=$id?q('SELECT * FROM offers WHERE id=?',[$id])->fetch():null;$items=$id?q('SELECT * FROM offer_items WHERE offer_id=? ORDER BY sort_order,id',[$id])->fetchAll():[];$ts=q('SELECT * FROM tenants ORDER BY name')->fetchAll();$packs=q('SELECT * FROM price_packages WHERE active=1 ORDER BY sort_order,id')->fetchAll();$addons=q('SELECT * FROM commercial_modules WHERE active=1 ORDER BY sort_order,id')->fetchAll();if(!$o)$o=['offer_no'=>next_offer_no(),'status'=>'DRAFT','tax_rate'=>17,'valid_until'=>date('Y-m-d',strtotime('+15 days'))];if($id&&($_GET['mode']??'')==='presentation'){?><!doctype html><html lang="bs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=e($o['offer_no'])?> · MMC ERP</title><link rel="stylesheet" href="public/style.css"></head><body class="presentation-body"><div class="presentation-shell offer-presentation"><header class="presentation-head"><div><span class="cc-kicker">MMC ERP · PONUDA</span><h1><?=e($o['offer_no'])?></h1><p><?=e($o['customer_name'])?></p></div><div class="presentation-actions"><a class="btn" href="?page=offer&id=<?=$id?>">Uredi</a><a class="btn" href="?page=pricing&mode=presentation">Paketi</a></div></header><section class="offer-summary-card"><div class="offer-customer"><span>KUPAC</span><b><?=e($o['customer_name'])?></b><small><?=e($o['customer_address']??'')?></small></div><div class="offer-valid"><span>VRIJEDI DO</span><b><?=e($o['valid_until']??'—')?></b></div></section><section class="offer-lines-present"><?php foreach($items as $it):?><div class="offer-line-present"><div><b><?=e($it['description'])?></b><small><?=e((string)$it['qty'])?> <?=e($it['unit'])?> × <?=money_bam((float)$it['unit_price'])?><?=((float)$it['discount_pct']>0)?' · popust '.e((string)$it['discount_pct']).'%':''?></small></div><strong><?=money_bam((float)$it['line_total'])?></strong></div><?php endforeach;?></section><section class="offer-total-present"><div><span>Osnovica</span><b><?=money_bam((float)$o['subtotal']-(float)$o['discount_total'])?></b></div><div><span>PDV <?=e((string)$o['tax_rate'])?>%</span><b><?=money_bam((float)$o['tax_total'])?></b></div><div class="grand"><span>UKUPNO</span><b><?=money_bam((float)$o['total'])?></b></div></section><?php if(!empty($o['notes'])):?><section class="offer-note-present"><?=nl2br(e($o['notes']))?></section><?php endif;?><footer class="presentation-foot"><span>M-M-C d.o.o. · MMC ERP Platform</span><b><?=date('d.m.Y.')?></b></footer></div></body></html><?php exit;}layout_top($id?'Ponuda '.$o['offer_no']:'Nova ponuda');if(isset($_GET['saved']))echo '<div class="alert ok">Ponuda je spremljena.</div>';?>
 <form method="post" class="panel offer-form" id="offerForm"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_offer"><input type="hidden" name="id" value="<?=$id?>"><div class="form-grid"><label>Broj ponude<input name="offer_no" value="<?=e($o['offer_no'])?>" required></label><label>ERP firma / tenant<select name="tenant_id" id="offerTenant"><option value="">— Novi kupac / bez tenanta —</option><?php foreach($ts as $t):?><option value="<?=$t['id']?>" data-name="<?=e($t['name'])?>" data-address="<?=e(trim(($t['address']??'').' '.($t['postal_code']??'').' '.($t['city']??'')))?>" data-jib="<?=e($t['jib']??'')?>" data-pdv="<?=e($t['pdv']??'')?>" <?=((int)($o['tenant_id']??0)===(int)$t['id'])?'selected':''?>><?=e($t['name'])?></option><?php endforeach;?></select></label><label>Naziv kupca<input id="customerName" name="customer_name" value="<?=e($o['customer_name']??'')?>" required></label><label>Adresa<input id="customerAddress" name="customer_address" value="<?=e($o['customer_address']??'')?>"></label><label>JIB<input id="customerJib" name="customer_jib" value="<?=e($o['customer_jib']??'')?>"></label><label>PDV broj<input id="customerPdv" name="customer_pdv" value="<?=e($o['customer_pdv']??'')?>"></label><label>Status<select name="status"><?php foreach(['DRAFT'=>'Nacrt','SENT'=>'Poslana','ACCEPTED'=>'Prihvaćena','REJECTED'=>'Odbijena','EXPIRED'=>'Istekla'] as $k=>$v):?><option value="<?=$k?>" <?=$k===($o['status']??'DRAFT')?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><label>Vrijedi do<input type="date" name="valid_until" value="<?=e($o['valid_until']??'')?>"></label></div>
 <div class="offer-preset"><b>Dodaj iz cjenika:</b><?php foreach($packs as $p):?><button type="button" class="btn small preset-btn" data-name="Implementacija MMC ERP <?=e($p['name'])?>" data-price="<?=$p['implementation_price']?>">+ <?=e($p['name'])?> implementacija</button><button type="button" class="btn small preset-btn" data-name="MMC ERP <?=e($p['name'])?> – licenca, hosting, održavanje i nadogradnje / 12 mjeseci" data-price="<?=$p['annual_price']?>">+ <?=e($p['name'])?> godišnje</button><?php endforeach;?><?php foreach($addons as $m):?><button type="button" class="btn small preset-btn addon-preset" data-name="<?=e($m['name'])?> – 12 mjeseci" data-price="<?=$m['annual_price']?>">+ <?=e($m['name'])?></button><?php endforeach;?></div>
 <div class="table-wrap"><table class="offer-items"><thead><tr><th>Opis</th><th>Kol.</th><th>JM</th><th>Cijena</th><th>Popust %</th><th></th></tr></thead><tbody id="offerItems"><?php $render=$items?:[['description'=>'','qty'=>1,'unit'=>'kom','unit_price'=>0,'discount_pct'=>0]];foreach($render as $it):?><tr><td><input name="item_description[]" value="<?=e((string)$it['description'])?>" required></td><td><input type="number" step="0.001" name="item_qty[]" value="<?=$it['qty']?>"></td><td><input name="item_unit[]" value="<?=e((string)$it['unit'])?>"></td><td><input type="number" step="0.01" name="item_price[]" value="<?=$it['unit_price']?>"></td><td><input type="number" step="0.01" name="item_discount[]" value="<?=$it['discount_pct']?>"></td><td><button type="button" class="btn small remove-row">×</button></td></tr><?php endforeach;?></tbody></table></div><button type="button" class="btn" id="addRow">+ Stavka</button>
 <div class="form-grid offer-bottom"><label>PDV stopa %<input type="number" step="0.01" name="tax_rate" value="<?=$o['tax_rate']?>"></label><label class="wide">Napomena<textarea name="notes" rows="4"><?=e($o['notes']??'')?></textarea></label></div><div class="offer-save"><div class="offer-save-actions"><button class="btn primary">Spremi ponudu</button><?php if($id):?><a class="btn" href="?page=offer&id=<?=$id?>&mode=presentation">▣ Prezentacija</a><?php endif;?></div><?php if($id):?><span>Bez PDV: <b><?=money_bam((float)$o['subtotal']-(float)$o['discount_total'])?></b> · PDV: <b><?=money_bam((float)$o['tax_total'])?></b> · Ukupno: <b><?=money_bam((float)$o['total'])?></b></span><?php endif;?></div></form>
 <script>(function(){const body=document.getElementById('offerItems');function bind(){body.querySelectorAll('.remove-row').forEach(b=>b.onclick=()=>{if(body.rows.length>1)b.closest('tr').remove();});}function add(n='',p='0'){const tr=document.createElement('tr');tr.innerHTML='<td><input name="item_description[]" required></td><td><input type="number" step="0.001" name="item_qty[]" value="1"></td><td><input name="item_unit[]" value="kom"></td><td><input type="number" step="0.01" name="item_price[]"></td><td><input type="number" step="0.01" name="item_discount[]" value="0"></td><td><button type="button" class="btn small remove-row">×</button></td>';tr.querySelector('[name="item_description[]"]').value=n;tr.querySelector('[name="item_price[]"]').value=p;body.appendChild(tr);bind();}document.getElementById('addRow').onclick=()=>add();document.querySelectorAll('.preset-btn').forEach(b=>b.onclick=()=>add(b.dataset.name,b.dataset.price));const t=document.getElementById('offerTenant');t.onchange=()=>{const x=t.options[t.selectedIndex];if(!x.value)return;document.getElementById('customerName').value=x.dataset.name||'';document.getElementById('customerAddress').value=x.dataset.address||'';document.getElementById('customerJib').value=x.dataset.jib||'';document.getElementById('customerPdv').value=x.dataset.pdv||'';};bind();})();</script>
 <?php layout_bottom();exit;
}
if($page==='inquiries'){
 layout_top('Upiti');
 $stF=(string)($_GET['status']??'');$kq=trim((string)($_GET['q']??''));$w=[];$pr=[];
 if(isset(inquiry_statuses()[$stF])){$w[]='status=?';$pr[]=$stF;}
 if($kq!==''){$w[]='(company_name LIKE ? OR contact_name LIKE ? OR email LIKE ? OR ref_no LIKE ?)';array_push($pr,...array_fill(0,4,'%'.$kq.'%'));}
 $rows=q('SELECT * FROM inquiries'.($w?' WHERE '.implode(' AND ',$w):'').' ORDER BY (status=\'NEW\') DESC,id DESC LIMIT 300',$pr)->fetchAll();
 $cnt=[];foreach(q('SELECT status,COUNT(*) n FROM inquiries GROUP BY status')->fetchAll() as $r)$cnt[$r['status']]=(int)$r['n'];
 $openVal=(float)q("SELECT COALESCE(SUM(total_net),0) FROM inquiries WHERE status IN ('NEW','IN_PROGRESS','OFFER_SENT')")->fetchColumn();
 if(isset($_GET['deleted']))echo '<div class="alert ok">Upit je obrisan.</div>';
 ?><section class="cc-toolbar"><div><h2>Upiti s javnog cjenika</h2><p>Upiti kupaca i knjigovođa poslani preko <a href="<?=e(pub_site_url())?>/cjenik" target="_blank" rel="noopener"><?=e(preg_replace('~^https?://~','',pub_site_url()))?>/cjenik</a> stižu ovdje s konfiguracijom i pitanjima.</p></div><div><a class="btn" href="<?=e(pub_site_url())?>/cjenik" target="_blank" rel="noopener">Otvori javnu stranicu ↗</a><a class="btn" href="?page=pricing">Uredi cjenik</a></div></section>
 <section class="kpis kpis-pro"><div><small>NOVI</small><b class="<?=($cnt['NEW']??0)?'agent-off':''?>"><?=(int)($cnt['NEW']??0)?></b><span>Čekaju prvi odgovor</span></div><div><small>U OBRADI</small><b><?=(int)($cnt['IN_PROGRESS']??0)?></b><span>Razgovor u toku</span></div><div><small>PONUDA POSLANA</small><b><?=(int)($cnt['OFFER_SENT']??0)?></b><span>Čeka odluku kupca</span></div><div><small>OTVORENO (BEZ PDV)</small><b><?=e(money_bam($openVal))?></b><span>Prvi obračun po otvorenim upitima</span></div></section>
 <form method="get" class="inq-filter"><input type="hidden" name="page" value="inquiries"><div class="inq-tabs"><a class="<?=$stF===''?'on':''?>" href="?page=inquiries">Svi <em><?=array_sum($cnt)?></em></a><?php foreach(inquiry_statuses() as $k=>$l):?><a class="<?=$stF===$k?'on':''?>" href="?page=inquiries&status=<?=$k?>"><?=e($l)?> <em><?=(int)($cnt[$k]??0)?></em></a><?php endforeach;?></div><input type="search" name="q" value="<?=e($kq)?>" placeholder="Pretraga: firma, osoba, email, broj…"><?php if($stF!==''):?><input type="hidden" name="status" value="<?=e($stF)?>"><?php endif;?><button class="btn">Traži</button></form>
 <?php if(!$rows):?><div class="empty-state panel"><b><?=($w?'Nema upita za zadani filter.':'Još nema upita.')?></b><p>Kad posjetitelj pošalje upit preko javnog cjenika, pojavit će se ovdje i dobit ćete obavijest emailom.</p></div><?php else:?>
 <div class="table-wrap"><table><thead><tr><th>Broj</th><th>Primljeno</th><th>Firma / kontakt</th><th>Vrsta</th><th>Konfiguracija</th><th>Bez PDV-a</th><th>Status</th><th></th></tr></thead><tbody>
 <?php foreach($rows as $r):$cf=json_decode((string)$r['config_json'],true)?:[];$isNew=$r['status']==='NEW';?>
 <tr class="<?=$isNew?'inq-new':''?>"><td><b><a href="?page=inquiry&id=<?=$r['id']?>"><?=e($r['ref_no'])?></a></b></td><td><?=e(fmt_dt($r['created_at']))?></td><td><b><?=e($r['company_name'])?></b><small class="cell-sub"><?=e($r['contact_name'])?> · <?=e($r['email'])?></small></td><td><?=$r['kind']==='ACCOUNTANT'?badge('Knjigovođa','ok'):badge('Firma','ok')?></td>
 <td><?php if($r['kind']==='ACCOUNTANT'):?><?=(int)($cf['clients']??0)?> klijenata<?php else:?><?=e((string)$r['package_code'])?> · <?=e(PUB_CYCLES[$r['billing_cycle']??''][0]??'')?><small class="cell-sub"><?=count((array)($cf['addons']??[]))?> dod. modula<?=!empty($cf['verticals'])?' · vertikala':''?></small><?php endif;?></td>
 <td class="nowrap"><?=$r['kind']==='ACCOUNTANT'?'—':e(money_bam((float)$r['total_net']))?></td><td><?=inquiry_status_badge((string)$r['status'])?></td><td class="nowrap"><a class="btn small<?=$isNew?' primary':''?>" href="?page=inquiry&id=<?=$r['id']?>">Otvori</a></td></tr>
 <?php endforeach;?></tbody></table></div><?php endif;
 layout_bottom();exit;
}
if($page==='inquiry'){
 $id=(int)($_GET['id']??0);$r=q('SELECT * FROM inquiries WHERE id=?',[$id])->fetch();
 if(!$r){$flash='Upit nije pronađen.';layout_top('Upit');echo '<a class="btn" href="?page=inquiries">← Svi upiti</a>';layout_bottom();exit;}
 $cf=json_decode((string)$r['config_json'],true)?:[];$dt=json_decode((string)$r['details_json'],true)?:[];$defs=module_definitions();
 $lab=['DATECS'=>'Datecs','TRING'=>'Tring','NONE'=>'Ne koristi','UNKNOWN'=>'Ne zna','YES'=>'Da','NO'=>'Ne','ASAP'=>'Što prije','1M'=>'U roku mjesec dana','3M'=>'U roku tri mjeseca','LATER'=>'Još razmišlja','email'=>'Emailom','phone'=>'Telefonom'];
 $L=fn($k)=>$lab[$dt[$k]??'']??($dt[$k]??'—');
 $profiles=['retail'=>'Trgovina / maloprodaja','optika'=>'Optika','moto'=>'Moto / vozila i servis','other'=>'Nešto drugo'];
 $off=!empty($r['offer_id'])?q('SELECT id,offer_no FROM offers WHERE id=?',[(int)$r['offer_id']])->fetch():null;
 layout_top('Upit '.$r['ref_no']);
 if(isset($_GET['saved']))echo '<div class="alert ok">Promjene su spremljene.</div>';
 ?><div class="inq-back"><a class="btn small" href="?page=inquiries">← Svi upiti</a> <?=inquiry_status_badge((string)$r['status'])?> <span class="muted">Primljeno <?=e(fmt_dt($r['created_at']))?> · <?=$r['kind']==='ACCOUNTANT'?'upit knjigovođe':'upit firme'?><?=$r['notified']?'':' · email obavijest nije poslana'?></span></div>
 <div class="inq-grid">
  <div class="inq-col">
   <section class="panel"><div class="section-head"><h2><?=e($r['company_name'])?></h2></div>
    <div class="system-list"><div><span>Kontakt osoba</span><b><?=e($r['contact_name'])?></b></div><div><span>Email</span><b><a href="mailto:<?=e($r['email'])?>"><?=e($r['email'])?></a></b></div><div><span>Telefon</span><b><a href="tel:<?=e(preg_replace('/[^0-9+]/','',$r['phone']))?>"><?=e($r['phone'])?></a></b></div><div><span>Mjesto</span><b><?=e((string)$r['city']?:'—')?></b></div><div><span>JIB</span><b><?=e((string)$r['jib']?:'—')?></b></div><div><span>PDV broj</span><b><?=e((string)$r['pdv']?:'—')?></b></div><div><span>Preferira kontakt</span><b><?=e($L('contact_pref'))?></b></div>
    <?php if($r['kind']==='ACCOUNTANT'):?><div><span>Broj klijenata</span><b><?=(int)($dt['clients']??0)?></b></div><?php else:?><div><span>Djelatnost</span><b><?=e($profiles[$r['profile']??'']??'—')?></b></div><?php endif;?></div></section>
   <section class="panel"><div class="section-head"><h2>Pitanja i napomene kupca</h2></div><?php if($r['message']):?><div class="inq-msg"><?=nl2br(e((string)$r['message']))?></div><?php else:?><p class="muted">Kupac nije upisao pitanja.</p><?php endif;?></section>
   <?php if($r['kind']==='COMPANY'):?><section class="panel"><div class="section-head"><h2>O poslovanju</h2></div><div class="system-list"><div><span>Broj korisnika</span><b><?=(int)($dt['users']??0)?:'—'?></b></div><div><span>Lokacije</span><b><?=(int)($dt['locations']??0)?:'—'?></b></div><div><span>Blagajne (POS)</span><b><?=(int)($dt['pos']??0)?:'—'?></b></div><div><span>Fiskalni uređaj</span><b><?=e($L('fiscal'))?></b></div><div><span>Uvoz podataka</span><b><?=e($L('migration'))?></b></div><div><span>Sadašnji program</span><b><?=e((string)($dt['current_software']??'')?:'—')?></b></div><div><span>Želi početi</span><b><?=e($L('start'))?></b></div></div></section><?php endif;?>
  </div>
  <div class="inq-col">
   <section class="panel"><div class="section-head"><h2><?=$r['kind']==='ACCOUNTANT'?'Partnerski upit':'Konfiguracija'?></h2><?php if($r['kind']==='COMPANY'):?><span class="core-pill"><?=e((string)$r['package_code'])?> · <?=e(PUB_CYCLES[$r['billing_cycle']??''][0]??'')?></span><?php endif;?></div>
   <?php if($r['kind']==='COMPANY'&&!empty($cf['lines'])):?>
    <div class="table-wrap"><table><tbody><?php foreach($cf['lines'] as $ln):?><tr><td><?=e((string)$ln['label'])?><?php if(($ln['k']??'')==='svc'):?> <small class="cell-sub">procjena usluge</small><?php endif;?></td><td class="nowrap" style="text-align:right"><b><?=($ln['k']??'')==='quote'?'po dogovoru':e(money_bam((float)$ln['amount']))?></b></td></tr><?php endforeach;?></tbody></table></div>
    <div class="inq-tot"><div><span>Ukupno bez PDV-a</span><b><?=e(money_bam((float)$r['total_net']))?></b></div><div><span>PDV (<?=e((string)($cf['vat_pct']??PUB_VAT))?>%)</span><b><?=e(money_bam((float)$cf['vat']))?></b></div><div class="inq-gross"><span>Ukupno sa PDV-om</span><b><?=e(money_bam((float)$r['total_gross']))?></b></div></div>
    <?php if(!empty($cf['saving'])):?><p class="muted">Uz izabrani period kupac štedi <?=e(money_bam((float)$cf['saving']))?> u odnosu na mjesečno plaćanje. Usluge (procjena) nisu uračunate u ukupno.</p><?php endif;?>
    <?php if(!empty($cf['verticals'])):?><p class="muted">Vertikalni moduli (cijena po dogovoru): <?=e(implode(', ',array_map(fn($k)=>$defs[$k]['name']??$k,$cf['verticals'])))?></p><?php endif;?>
   <?php elseif($r['kind']==='ACCOUNTANT'):?>
    <div class="system-list"><div><span>Klijenata (procjena)</span><b><?=(int)($cf['clients']??0)?></b></div><?php if(isset($cf['est_monthly_commission'])):?><div><span>Modul po klijentu</span><b><?=e(money_bam((float)$cf['module_monthly']))?> / mj.</b></div><div><span>Provizija (<?=e((string)$cf['commission_pct'])?>%)</span><b><?=e(money_bam((float)$cf['est_monthly_commission']))?> / mj.</b></div><div><span>Jednokratni bonusi</span><b><?=e(money_bam((float)$cf['est_bonus_total']))?></b></div><?php endif;?></div>
    <p class="muted">Za unos u evidenciju partnera otvori <a href="?page=accountants">Knjigovođe</a>.</p>
   <?php else:?><p class="muted">Nema sačuvane konfiguracije.</p><?php endif;?></section>
   <form method="post" class="panel inq-act"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="inquiry_update"><input type="hidden" name="id" value="<?=$r['id']?>">
    <div class="section-head"><h2>Obrada</h2></div>
    <label>Status<select name="status"><?php foreach(inquiry_statuses() as $k=>$l):?><option value="<?=$k?>" <?=$r['status']===$k?'selected':''?>><?=e($l)?></option><?php endforeach;?></select></label>
    <label>Interna bilješka <small>(ne vidi je kupac)</small><textarea name="internal_note" rows="4" placeholder="Dogovor, pitanja za kupca, sljedeći korak…"><?=e((string)($r['internal_note']??''))?></textarea></label>
    <div class="inq-btns"><button class="btn primary">Spremi</button>
     <a class="btn" href="mailto:<?=e($r['email'])?>?subject=<?=rawurlencode('Vaš upit '.$r['ref_no'].' — MMC ERP')?>">Odgovori emailom</a></div>
   </form>
   <?php if($r['kind']==='COMPANY'&&!empty($cf['lines'])):?><section class="panel"><div class="section-head"><h2>Ponuda</h2></div>
    <?php if($off):?><p>Ponuda <b><?=e($off['offer_no'])?></b> je već napravljena iz ovog upita.</p><a class="btn primary" href="?page=offer&id=<?=$off['id']?>">Otvori ponudu</a>
    <?php else:?><p class="muted">Kreira nacrt ponude s ovim stavkama i podacima kupca (vrijedi 30 dana). Možeš je urediti prije slanja.</p><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="inquiry_to_offer"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn primary">Kreiraj ponudu iz upita</button></form><?php endif;?></section><?php endif;?>
   <?php if(is_admin()):?><form method="post" class="inq-del" onsubmit="return confirm('Trajno obrisati ovaj upit?');"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="inquiry_delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn small danger">Obriši upit</button></form><?php endif;?>
  </div>
 </div><?php
 layout_bottom();exit;
}
if($page==='updates'){
 layout_top('Update Center');
 $versions=q('SELECT * FROM core_versions ORDER BY id DESC')->fetchAll();
 $ts=q('SELECT * FROM tenants ORDER BY name')->fetchAll();
 $packs=q('SELECT * FROM update_packages WHERE archived_at IS NULL ORDER BY id DESC')->fetchAll();
 /* v1.8.0: ?tenant=ID prikazuje samo pakete kompatibilne s tom firmom (link "Nadogradnje" s kartice firme). */
 $ft=null;if(!empty($_GET['tenant'])){$ft=q('SELECT * FROM tenants WHERE id=?',[(int)$_GET['tenant']])->fetch()?:null;if($ft)$packs=array_values(array_filter($packs,fn($p)=>package_target_ok($ft,$p)));}
 $archived=q('SELECT * FROM update_packages WHERE archived_at IS NOT NULL ORDER BY archived_at DESC,id DESC')->fetchAll();
 $deps=q('SELECT d.*,t.name tenant_name FROM deployments d JOIN tenants t ON t.id=d.tenant_id ORDER BY d.id DESC LIMIT 30')->fetchAll();
 $rollouts=q('SELECT r.*,p.version,p.name package_name FROM update_rollouts r LEFT JOIN update_packages p ON p.id=r.package_id ORDER BY r.id DESC LIMIT 15')->fetchAll();
 foreach(['health'=>'Agent je dostupan i stanje instance je osvježeno.','package'=>'Update paket je spremljen; podaci su automatski učitani iz manifesta.','deployed'=>'Nadogradnja je završena i health provjera je prošla.','rollback'=>'Rollback je završen.','archived'=>'Paket je arhiviran.','restored'=>'Paket je vraćen iz arhive.','deleted'=>'Paket je trajno obrisan.'] as $k=>$msg)if(isset($_GET[$k]))echo '<div class="alert ok">'.e($msg).'</div>';
 ?>
 <?php if(isset($_GET['cleaned'])){echo '<div class="alert '.(isset($_GET['cleanfail'])?'err':'ok').'">Čišćenje paketa: obrisano '.(int)$_GET['cleaned'].' ZIP datoteka ('.e(fmt_bytes((int)($_GET['freed']??0))).' oslobođeno), ažurirano '.(int)($_GET['rows']??0).' zapisa.'.(isset($_GET['cleanfail'])?' Neuspjelo: '.(int)$_GET['cleanfail'].' (vidi Audit).':'').'</div>';}
 if(($_GET['cleanup']??'')==='preview'&&is_admin()){$plan=pkg_cleanup_plan();?>
 <section class="panel" id="package-cleanup"><div class="section-head"><div><h2>Očisti stare pakete — pregled (dry-run)</h2><p>Ništa još nije obrisano. Zadržava se: najnovija verzija po cilju/opsegu, paketi u rolloutu koji nije završen i STABILNI paketi koje firme trenutno vide u nadogradnji.</p></div><a class="btn" href="?page=updates">Odustani</a></div>
 <?php if(!$plan['items']&&!$plan['orphans']):?><div class="empty-state">Nema starih paketa za čišćenje.</div><?php else:?>
 <div class="table-wrap"><table><thead><tr><th>Paket</th><th>Datoteka</th><th>Veličina</th><th>Razlog</th><th>Što se radi</th></tr></thead><tbody>
 <?php foreach($plan['items'] as $it):?><tr><td><b><?=e($it['version'])?></b><small class="cell-sub"><?=e($it['name'])?> · #<?=(int)$it['id']?></small></td><td><small><?=e($it['file'])?></small></td><td><?=$it['has_file']?e(fmt_bytes($it['size'])):'—'?></td><td><?=e($it['reason'])?></td><td><?=$it['mode']==='delete'?'briše se ZIP i zapis':'briše se ZIP; zapis ostaje u arhivi (povijest deploymenta)'?></td></tr><?php endforeach;?>
 <?php foreach($plan['orphans'] as $o):?><tr><td><i>bez zapisa u bazi</i></td><td><small><?=e($o['file'])?></small></td><td><?=e(fmt_bytes($o['size']))?></td><td>ZIP nije povezan ni s jednim paketom</td><td>briše se ZIP (ako je označeno ispod)</td></tr><?php endforeach;?>
 </tbody></table></div>
 <form method="post" class="inline-form" onsubmit="return confirm('Trajno obrisati navedene ZIP pakete? Radnja se ne može poništiti.');"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="package_cleanup"><input type="hidden" name="plan" value="<?=e($plan['hash'])?>"><?php if($plan['orphans']):?><label class="checkline"><input type="checkbox" name="orphans" value="1" checked> Obriši i <?=count($plan['orphans'])?> ZIP datoteka bez zapisa u bazi</label> <?php endif;?><button class="btn primary">Potvrdi čišćenje (<?=count($plan['items'])+count($plan['orphans'])?> stavki, do <?=e(fmt_bytes($plan['bytes']))?>)</button></form>
 <?php endif;?>
 <details class="update-upload"><summary>Zadržava se (<?=count($plan['kept'])?>)</summary><div class="table-wrap"><table><tbody><?php foreach($plan['kept'] as $k):?><tr><td><b><?=e((string)$k['version'])?></b> <small><?=e((string)$k['name'])?> · #<?=(int)$k['id']?></small></td><td><?=e(fmt_bytes((int)$k['size']))?></td><td><?=e($k['reason'])?></td></tr><?php endforeach;?></tbody></table></div></details>
 </section><?php }
 if(isset($_GET['channel']))echo '<div class="alert ok">Status paketa je promijenjen.</div>';if(isset($_GET['rollout']))echo '<div class="alert ok">Rollout #'.(int)$_GET['rollout'].' je završen. Rezultati su evidentirani po firmama.</div>'; ?>
 <?php if($ft):$fst=tenant_update_state($ft);?><section class="panel tenant-filter"><div><span class="cc-kicker">PRIKAZ ZA FIRMU</span><h2><?=e($ft['name'])?></h2><p>Instalirano: <b>Core <?=e($ft['installed_version']?:'—')?></b> · <?=e(tenant_profiles()[tenant_app_type($ft)]??'')?> · Agent: <?=e(agent_status_label($ft))?> · <?=badge($fst['label'],$fst['state']==='current'?'ok':'warn')?></p><small>Prikazano je <?=count($packs)?> paketa kompatibilnih s ovom firmom (profil, slug, core_from).</small></div><a class="btn" href="?page=updates">Prikaži sve pakete</a></section><?php endif;?>
 <div class="alert info"><b>Smart Update Center (CC v<?=e(cc_version())?>):</b> podržava COMMON, PROFILE i TENANT pakete. Kompatibilnost se provjerava prema profilu firme, tenant slug-u i <code>core_from</code>; nakon deploymenta stvarna verzija se ponovno čita iz Health Agenta.</div>
 <section class="panel"><div class="section-head"><h2>ERP instance i agenti</h2><span class="core-pill">Control Center v<?=e(cc_version())?></span></div><div class="table-wrap"><table><thead><tr><th>Firma</th><th>Core</th><th>Agent</th><th>Zadnja provjera</th><th>Akcija</th></tr></thead><tbody><?php foreach($ts as $t):$on=agent_status_label($t)==='ONLINE';?><tr><td><b><?=e($t['name'])?></b><small class="cell-sub"><?=e(parse_url($t['base_url'],PHP_URL_HOST)?:$t['base_url'])?></small></td><td><?=e($t['installed_version'])?></td><td><?=badge($on?'ONLINE':'NIJE POVEZAN',$on?'ok':'warn')?><small class="cell-sub"><?=e($t['agent_version']??'')?></small></td><td><?=e($t['last_health_at']??'—')?></td><td><form method="post" class="inline-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="agent_health"><input type="hidden" name="tenant_id" value="<?=$t['id']?>"><button class="btn small">Testiraj agent</button></form> <a class="btn small" href="?page=tenant&id=<?=$t['id']?>">Postavke</a></td></tr><?php endforeach;?></tbody></table></div></section>
 <section class="panel"><div class="section-head"><div><h2>Paketi za nadogradnju</h2><p>Aktivni paketi spremni za deployment.</p></div><?php if(is_admin()):?><a class="btn" href="?page=updates&cleanup=preview#package-cleanup">Očisti stare pakete</a><?php endif;?></div>
 <?php if($packs):?><div class="update-packages"><?php foreach($packs as $p):$compatible=array_values(array_filter($ts,fn($t)=>package_target_ok($t,$p)));?><article class="update-package rollout-package"><div><b>Core <?=e($p['version'])?> · <?=e($p['theme']?:$p['name'])?></b><span class="target-pill"><?=e(strtoupper(package_scope($p)))?> · <?=e(strtoupper($p['target_app']?:'ALL'))?></span><span class="release-pill <?=strtolower(e($p['release_channel']??'DRAFT'))?>"><?=e($p['release_channel']??'DRAFT')?></span><small><?=e($p['name'])?> · <?=number_format(((int)$p['size_bytes'])/1024,1,',','.')?> KB · <?=count($compatible)?> kompatibilnih firmi</small><p><?=e($p['short_description']?:($p['notes']??''))?></p></div><div class="package-actions rollout-actions"><form method="post" class="rollout-form" onsubmit="return confirm('Primijeniti ovaj paket na sve označene firme? Za svaku firmu agent prvo radi backup.');"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="deploy_package_batch"><input type="hidden" name="package_id" value="<?=$p['id']?>"><div class="rollout-tenants"><div class="rollout-select-head"><b>Odaberi firme</b><button type="button" class="btn small select-all-compatible">Sve</button></div><?php foreach($compatible as $t):?><label><input type="checkbox" name="tenant_ids[]" value="<?=$t['id']?>"><span><b><?=e($t['name'])?></b><small><?=e(strtoupper(tenant_app_type($t)))?> · <?=e($t['installed_version'])?> · <?=e(agent_status_label($t))?></small></span></label><?php endforeach;?><?php if(!$compatible):?><small>Nema kompatibilnih firmi.</small><?php endif;?></div><button class="btn primary" <?=$compatible?'':'disabled'?>>Primijeni na odabrane (<?=count($compatible)?>)</button></form><form method="post" class="channel-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="set_package_channel"><input type="hidden" name="package_id" value="<?=$p['id']?>"><select name="release_channel" onchange="this.form.submit()"><?php foreach(['DRAFT'=>'Nacrt','PILOT'=>'Pilot','STABLE'=>'Stabilna'] as $k=>$v):?><option value="<?=$k?>" <?=$k===($p['release_channel']??'DRAFT')?'selected':''?>><?=$v?></option><?php endforeach;?></select></form><form method="post" class="inline-form" onsubmit="return confirm('Arhivirati ovaj update paket?');"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="archive_package"><input type="hidden" name="package_id" value="<?=$p['id']?>"><button class="btn small">Arhiviraj</button></form></div></article><?php endforeach;?></div><?php else:?><div class="empty-state">Nema aktivnih update paketa.</div><?php endif;?>
 <details class="update-upload"><summary>+ Dodaj novi Core / tenant update ZIP</summary><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="upload_package"><label class="wide">ZIP paket<input type="file" name="package" accept=".zip,application/zip" required></label><div class="wide"><small>Podaci se čitaju iz <b>mmc-update.json</b>. Podržani su <code>package_scope</code>, <code>compatible_profiles</code>, <code>tenant_slugs</code> i <code>core_from</code>.</small></div><div class="wide"><button class="btn primary">Učitaj i spremi paket</button></div></form></details>
 <?php if($archived):?><details class="update-upload"><summary>Arhiva update paketa (<?=count($archived)?>)</summary><div class="update-packages"><?php foreach($archived as $p):?><article class="update-package"><div><b>Core <?=e($p['version'])?> · <?=e($p['theme']?:$p['name'])?></b><span class="target-pill"><?=e(strtoupper(package_scope($p)))?> · <?=e(strtoupper($p['target_app']?:'ALL'))?></span><small>Arhivirano <?=e($p['archived_at'])?><?=is_file(package_path($p))?'':' · ZIP obrisan (čuva se samo zapis)'?></small><p><?=e($p['short_description']?:($p['notes']??''))?></p></div><?php if(is_file(package_path($p))):?><form method="post" class="inline-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="restore_package"><input type="hidden" name="package_id" value="<?=$p['id']?>"><button class="btn small">Vrati iz arhive</button></form><?php endif;?></article><?php endforeach;?></div></details><?php endif;?>
 </section>
 <section class="panel"><div class="section-head"><h2>Rollout povijest</h2><span class="core-pill">MULTI-TENANT</span></div><div class="table-wrap"><table><thead><tr><th>Rollout</th><th>Paket</th><th>Rezultat</th><th>Status</th><th>Pokrenuo</th><th>Vrijeme</th></tr></thead><tbody><?php foreach($rollouts as $r):?><tr><td><b>#<?=$r['id']?></b></td><td><?=$r['version']!==null?e($r['version'].' · '.$r['package_name']):'<small>paket #'.(int)$r['package_id'].' obrisan</small>'?></td><td><b><?=e((string)$r['success_count'])?></b> uspješno · <b><?=e((string)$r['failed_count'])?></b> greška · <?=e((string)$r['tenant_count'])?> ukupno</td><td><?=badge($r['status'],$r['status']==='SUCCESS'?'ok':($r['status']==='RUNNING'?'info':'warn'))?></td><td><?=e($r['started_by']??'—')?></td><td><?=e($r['started_at'])?></td></tr><?php endforeach;?></tbody></table></div></section>
 <section class="panel"><div class="section-head"><h2>Povijest deploymenta</h2></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Firma</th><th>Verzija</th><th>Status</th><th>Backup</th><th>Vrijeme</th><th></th></tr></thead><tbody><?php foreach($deps as $d):?><tr><td>#<?=$d['id']?></td><td><?=e($d['tenant_name'])?></td><td><?=e(($d['from_version']??'—').' → '.($d['to_version']??'—'))?></td><td><?=badge($d['status'],in_array($d['status'],['SUCCESS','ROLLED_BACK'])?'ok':($d['status']==='FAILED'?'warn':'info'))?></td><td><small><?=e($d['backup_ref']??'—')?></small></td><td><?=e($d['started_at'])?></td><td><?php if($d['status']==='SUCCESS'&&!empty($d['backup_ref'])):?><form method="post" class="inline-form" onsubmit="return confirm('Vratiti ovu instancu na prethodnu verziju?');"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="rollback_deployment"><input type="hidden" name="deployment_id" value="<?=$d['id']?>"><button class="btn small danger-soft">Rollback</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
 <?php layout_bottom();exit;
}

if($page==='system'){
 $cleanRes=cc_root_cleanup_auto();if(!$cleanRes&&isset($_GET['rootclean'])){$cleanRes=$_SESSION['cc_cleanup_result']??null;unset($_SESSION['cc_cleanup_result']);}
 layout_top('Sistem');echo cc_cleanup_notice($cleanRes);$foreignNow=cc_foreign_present();
 $dbok=true; try{ q('SELECT 1')->fetchColumn(); }catch(Throwable $e){$dbok=false;}
 $storage=__DIR__.'/storage'; $w=is_dir($storage)&&is_writable($storage);
 $https=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off');
 ?>
 <section class="system-grid">
  <article class="system-card"><span class="sys-icon">PHP</span><div><small>Runtime</small><b><?=e(PHP_VERSION)?></b><em><?=badge('ONLINE','ok')?></em></div></article>
  <article class="system-card"><span class="sys-icon">DB</span><div><small>Baza platforme</small><b><?=$dbok?'Povezana':'Greška veze'?></b><em><?=badge($dbok?'ONLINE':'ERROR',$dbok?'ok':'warn')?></em></div></article>
  <article class="system-card"><span class="sys-icon">SSL</span><div><small>Sigurna veza</small><b><?=$https?'HTTPS aktivan':'Provjeri HTTPS'?></b><em><?=badge($https?'SECURE':'CHECK',$https?'ok':'warn')?></em></div></article>
  <article class="system-card"><span class="sys-icon">FS</span><div><small>Storage</small><b><?=$w?'Upis dozvoljen':'Nema write prava'?></b><em><?=badge($w?'READY':'CHECK',$w?'ok':'warn')?></em></div></article>
 </section>
 <section class="panel system-panel"><div class="section-head"><h2>Platforma</h2><span class="core-pill">MMC ERP Control Center v<?=e(cc_version())?></span></div>
 <div class="system-list"><div><span>Server vrijeme</span><b><?=date('d.m.Y. H:i:s')?></b></div><div><span>Web server</span><b><?=e($_SERVER['SERVER_SOFTWARE']??'—')?></b></div><div><span>Document root</span><b><?=e($_SERVER['DOCUMENT_ROOT']??'—')?></b></div><div><span>Session</span><b><?=session_status()===PHP_SESSION_ACTIVE?'Aktivna':'Nije aktivna'?></b></div><div><span>Root Control Centra</span><b><?=$foreignNow?count($foreignNow).' ERP datoteka — vidi upozorenje':'Čist (samo datoteke Control Centra)'?></b></div></div></section>
 <?php layout_bottom();exit;
}

if($page==='audit'){layout_top('Audit');$rows=q('SELECT * FROM audit_log ORDER BY id DESC LIMIT 200')->fetchAll();?><div class="table-wrap"><table><thead><tr><th>Vrijeme</th><th>Korisnik</th><th>Akcija</th><th>Entitet</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['created_at'])?></td><td><?=e($r['user_email'])?></td><td><?=e($r['action'])?></td><td><?=e(($r['entity']??'').' #'.($r['entity_id']??''))?></td></tr><?php endforeach;?></tbody></table></div><?php layout_bottom();exit;}
header('Location: ?page=dashboard');
