CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role VARCHAR(30) NOT NULL DEFAULT 'ADMIN',active TINYINT NOT NULL DEFAULT 1,created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;
CREATE TABLE IF NOT EXISTS tenants (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(190) NOT NULL,slug VARCHAR(100) NOT NULL UNIQUE,industry VARCHAR(120) NOT NULL,base_url VARCHAR(255) NOT NULL,db_name VARCHAR(120) NULL,installed_version VARCHAR(50) NOT NULL DEFAULT '',target_version VARCHAR(50) NOT NULL DEFAULT '',fiscal_driver VARCHAR(30) NOT NULL DEFAULT 'NONE',jib VARCHAR(20) NULL,pdv VARCHAR(20) NULL,status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',last_health_at DATETIME NULL,last_health_status VARCHAR(30) NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;
CREATE TABLE IF NOT EXISTS tenant_modules (id INT AUTO_INCREMENT PRIMARY KEY,tenant_id INT NOT NULL,module_key VARCHAR(80) NOT NULL,enabled TINYINT NOT NULL DEFAULT 1,UNIQUE KEY uq_tm(tenant_id,module_key),CONSTRAINT fk_tm_t FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;
CREATE TABLE IF NOT EXISTS core_versions (id INT AUTO_INCREMENT PRIMARY KEY,version VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(190) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',package_file VARCHAR(255) NULL,checksum VARCHAR(128) NULL,notes TEXT NULL,created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;
CREATE TABLE IF NOT EXISTS deployments (id INT AUTO_INCREMENT PRIMARY KEY,tenant_id INT NOT NULL,core_version_id INT NULL,from_version VARCHAR(50) NULL,to_version VARCHAR(50) NULL,status VARCHAR(30) NOT NULL,backup_ref VARCHAR(255) NULL,message TEXT NULL,started_at DATETIME NOT NULL,finished_at DATETIME NULL,CONSTRAINT fk_dep_t FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;
CREATE TABLE IF NOT EXISTS audit_log (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_email VARCHAR(190) NOT NULL,action VARCHAR(120) NOT NULL,entity VARCHAR(80) NULL,entity_id INT NULL,meta_json LONGTEXT NULL,created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;
